# Generated by Django 5.1.4 on 2023-03-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='about_me',
            field=models.TextField(blank=True, null=True, verbose_name='About Me'),
        ),
        migrations.AddField(
            model_name='resume',
            name='headline',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Headline'),
        ),
    ]
