# Generated by Django 5.1.3 on 2024-12-03 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('auth_account', '0001_initial'),
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='available_jobs',
            field=models.ManyToManyField(blank=True, to='common.job', verbose_name='Available Jobs'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(editable=False, related_name='users', to='common.skill', verbose_name='Skills'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='avatarfile',
            name='uploaded_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_avatar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='canadavisa',
            name='nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canada_visas', to='cities_light.country', verbose_name='Nationality'),
        ),
        migrations.AddField(
            model_name='canadavisa',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='canada_visa', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='certificateandlicense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='certificateandlicenseofflineverificationmethod',
            name='certificate_and_license',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth_account.certificateandlicense', verbose_name='Certificate And License'),
        ),
        migrations.AddField(
            model_name='certificateandlicenseonlineverificationmethod',
            name='certificate_and_license',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth_account.certificateandlicense', verbose_name='Certificate And License'),
        ),
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='education',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.field', verbose_name='Field'),
        ),
        migrations.AddField(
            model_name='education',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.university', verbose_name='University'),
        ),
        migrations.AddField(
            model_name='education',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='communicationmethod',
            name='education',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth_account.education', verbose_name='Education'),
        ),
        migrations.AddField(
            model_name='ieemethod',
            name='education',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth_account.education', verbose_name='Education'),
        ),
        migrations.AddField(
            model_name='languagecertificate',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='common.languageproficiencytest', verbose_name='Test'),
        ),
        migrations.AddField(
            model_name='languagecertificate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='offlinemethod',
            name='language_certificate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth_account.languagecertificate', verbose_name='Language Certificate'),
        ),
        migrations.AddField(
            model_name='onlinemethod',
            name='language_certificate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth_account.languagecertificate', verbose_name='Language Certificate'),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth_account.avatarfile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='profile',
            name='interested_jobs',
            field=models.ManyToManyField(blank=True, to='common.job', verbose_name='Interested Jobs'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='referencecheckemployer',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.position', verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='referencecheckemployer',
            name='work_experience_verification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employers', to='auth_account.employerlettermethod', verbose_name='Work Experience Verification'),
        ),
        migrations.AddField(
            model_name='referral',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referraluser',
            name='referral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_users', to='auth_account.referral'),
        ),
        migrations.AddField(
            model_name='referraluser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_source', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resume',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='cities_light.city', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='common.job', verbose_name='Job'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='paystubsmethod',
            name='work_experience',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth_account.workexperience', verbose_name='Work Experience'),
        ),
        migrations.AddField(
            model_name='employerlettermethod',
            name='work_experience',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth_account.workexperience', verbose_name='Work Experience'),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('user', 'type')},
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['code'], name='auth_accoun_code_3f95ce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='referraluser',
            unique_together={('referral', 'user')},
        ),
    ]
