# Generated by Django 5.1.1 on 2024-10-10 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0001_initial'),
        ('common', '0003_field_university_website'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Profile',
        ),
    ]
