# Generated by Django 5.1.1 on 2024-10-11 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0002_rename_userprofile_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communicationmethod',
            name='education_verification',
        ),
        migrations.RemoveField(
            model_name='ieemethod',
            name='education_verification',
        ),
        migrations.AddField(
            model_name='communicationmethod',
            name='education',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth_account.education', verbose_name='Education'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Is Verified'),
        ),
        migrations.AddField(
            model_name='education',
            name='method',
            field=models.CharField(choices=[('iee', 'International Education Evaluation'), ('communication', 'Communication'), ('self_verification', 'Self Verification')], default=None, max_length=50, verbose_name='Verification Method'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ieemethod',
            name='education',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth_account.education', verbose_name='Education'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='EducationVerification',
        ),
    ]
