# Generated by Django 5.1.4 on 2024-12-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0002_supportticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='description',
            field=models.TextField(max_length=1024),
        ),
    ]
