# Generated by Django 5.1.4 on 2024-12-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0003_alter_resume_resume_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='status_description',
            field=models.TextField(blank=True, null=True, verbose_name='Status Description'),
        ),
    ]
