# Generated by Django 5.1.4 on 2024-12-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0003_alter_supportticket_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencecheckemployer',
            name='position',
            field=models.CharField(max_length=255, verbose_name='Position'),
        ),
    ]
