# Generated by Django 5.1.3 on 2024-12-04 15:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0003_education_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='grade',
            field=models.CharField(choices=[('intern', 'Intern'), ('associate', 'Associate'), ('junior', 'Junior'), ('mid_level', 'Mid-Level'), ('senior', 'Senior'), ('manager', 'Manager'), ('director', 'Director'), ('cto', 'CTO'), ('cfo', 'CFO'), ('ceo', 'CEO')], default='junior', max_length=50, verbose_name='Grade'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, null=True, size=None, verbose_name='Skills'),
        ),
    ]
