# Generated by Django 5.1.1 on 2024-10-08 14:28

import colorfield.fields
import common.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpj_account', '0003_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('skin_color', colorfield.fields.ColorField(blank=True, choices=[('#FFDFC4', 'Very Fair'), ('#F0D5B1', 'Fair'), ('#E5B897', 'Light'), ('#D9A377', 'Light Medium'), ('#C68642', 'Medium'), ('#A86B33', 'Olive'), ('#8D5524', 'Brown'), ('#603913', 'Dark Brown'), ('#3B260B', 'Very Dark'), ('#100C08', 'Deep')], default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='Skin Color')),
                ('hair_color', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='Hair Color')),
                ('eye_color', colorfield.fields.ColorField(blank=True, choices=[('#FFBF00', 'Amber'), ('#5DADEC', 'Blue'), ('#6B4226', 'Brown'), ('#BEBEBE', 'Gray'), ('#1CAC78', 'Green'), ('#8E7618', 'Hazel'), ('#FF4500', 'Red'), ('#8F00FF', 'Violet')], default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='Eye Color')),
                ('full_body_image', models.ImageField(blank=True, null=True, upload_to='profile_images/', validators=[common.validators.ValidateFileSize(5)], verbose_name='Full Body Image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
