# Generated by Django 5.1.1 on 2024-10-14 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0004_profile_city_user_birth_date_user_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
