# Generated by Django 5.1.4 on 2024-12-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0004_alter_referencecheckemployer_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='score',
            field=models.IntegerField(default=0, editable=False, verbose_name='Score'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='scores',
            field=models.JSONField(default={}, editable=False, verbose_name='Scores'),
            preserve_default=False,
        ),
    ]
