# Generated by Django 5.1.1 on 2024-10-08 14:36

import account.models
import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpj_account', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='full_body_image',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.full_body_image_path, validators=[common.validators.ValidateFileSize(5)], verbose_name='Full Body Image'),
        ),
    ]
