# Generated by Django 5.1.3 on 2024-12-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0004_workexperience_grade_workexperience_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='grade',
            field=models.CharField(choices=[('intern', 'Intern'), ('associate', 'Associate'), ('junior', 'Junior'), ('mid_level', 'Mid-Level'), ('senior', 'Senior'), ('manager', 'Manager'), ('director', 'Director'), ('cto', 'CTO'), ('cfo', 'CFO'), ('ceo', 'CEO')], max_length=50, verbose_name='Grade'),
        ),
    ]
