# Generated by Django 5.1.4 on 2024-12-14 13:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0004_usertask_status_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperience',
            name='job',
        ),
        migrations.AddField(
            model_name='workexperience',
            name='job_title',
            field=models.CharField(default="job", max_length=255, verbose_name='Job Title'),
            preserve_default=False,
        ),
    ]
