# Generated by Django 5.1.1 on 2024-10-14 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0005_rename_phone_number_user_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
    ]
