# Generated by Django 5.1.3 on 2024-12-04 16:04

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0005_alter_workexperience_grade'),
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_profiles', to='cities_light.city', verbose_name='Job City'),
        ),
        migrations.AddField(
            model_name='profile',
            name='job_location_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('precise_location', 'On-site (Precise Location)'), ('limited_area', 'On-site (Within a Limited Area)'), ('remote', 'Remote'), ('hybrid', 'Hybrid'), ('on_the_road', 'On the road'), ('global', 'Global')], max_length=50), blank=True, null=True, size=None, verbose_name='Job Location Type'),
        ),
        migrations.AddField(
            model_name='profile',
            name='job_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('permanent', 'Permanent'), ('fix_term_contract', 'Fix Term Contract'), ('seasonal', 'Seasonal'), ('freelance', 'Freelance'), ('apprenticeship', 'Apprenticeship'), ('prince_edward_island', 'Prince Edward Island'), ('internship_co_op', 'Internship/Co-op')], max_length=50), blank=True, null=True, size=None, verbose_name='Job Type'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='cities_light.city', verbose_name='City'),
        ),
    ]
