# Generated by Django 5.1.4 on 2024-12-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0005_profile_score_profile_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Score'),
        ),
    ]
