# Generated by Django 5.1.4 on 2024-12-09 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0006_alter_profile_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='score',
        ),
    ]
