# Generated by Django 5.1.1 on 2024-10-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0006_alter_contact_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('website', 'Website'), ('address', 'Address'), ('linkedin', 'LinkedIn'), ('whatsapp', 'WhatsApp'), ('phone', 'Phone')], default='website', max_length=50, verbose_name='Type'),
        ),
    ]
