# Generated by Django 5.1.1 on 2024-10-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('cpj_account', '0006_userprofile_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='job',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='job',
            field=models.ManyToManyField(to='common.job', verbose_name='Job'),
        ),
    ]
