# Generated by Django 5.1.4 on 2024-12-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0006_profile_job_city_profile_job_location_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='skills',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Skills'),
        ),
    ]
