# Generated by Django 5.1.1 on 2024-12-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0006_alter_languagecertificate_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='category',
            field=models.CharField(choices=[('profile', 'Profile'), ('resume', 'Resume'), ('job_interest', 'Job Interest'), ('academy', 'Academy'), ('assessment', 'Assessment'), ('job_suggestion', 'Job Suggestion'), ('ai_interview', 'AI Interview')], max_length=50),
        ),
    ]
