# Generated by Django 5.1.1 on 2024-10-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('cpj_account', '0007_remove_userprofile_job_userprofile_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='job',
            field=models.ManyToManyField(blank=True, to='common.job', verbose_name='Job'),
        ),
    ]
