# Generated by Django 5.1.1 on 2023-03-16 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0007_alter_supportticket_category'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='industry',
            field=models.ForeignKey(default=98, on_delete=django.db.models.deletion.CASCADE, to='common.industry', verbose_name='Industry'),
            preserve_default=False,
        ),
    ]
