# Generated by Django 5.1.1 on 2024-10-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0007_remove_user_phone_alter_contact_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('employed', 'Employed'), ('unemployed', 'Unemployed'), ('student', 'Student')], max_length=50, null=True, verbose_name='Employment Status'),
        ),
    ]
