# Generated by Django 5.1.4 on 2024-12-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0007_remove_profile_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='scores',
            field=models.JSONField(default=dict, editable=False, verbose_name='Scores'),
        ),
    ]
