# Generated by Django 5.1.4 on 2024-12-08 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0007_alter_workexperience_skills'),
        ('common', '0008_delete_languageproficiencyresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='languagecertificate',
            options={'verbose_name': 'Language Proficiency Result', 'verbose_name_plural': 'Language Proficiency Results'},
        ),
        migrations.RemoveField(
            model_name='languagecertificate',
            name='band_score',
        ),
        migrations.RemoveField(
            model_name='languagecertificate',
            name='listening_score',
        ),
        migrations.RemoveField(
            model_name='languagecertificate',
            name='reading_score',
        ),
        migrations.RemoveField(
            model_name='languagecertificate',
            name='speaking_score',
        ),
        migrations.RemoveField(
            model_name='languagecertificate',
            name='test',
        ),
        migrations.RemoveField(
            model_name='languagecertificate',
            name='writing_score',
        ),
        migrations.AddField(
            model_name='languagecertificate',
            name='skill',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='common.languageproficiencyskill', verbose_name='Skill'),
            preserve_default=False,
        ),
    ]
