# Generated by Django 5.1.1 on 2024-12-14 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0006_alter_usertask_status'),
        ('auth_account', '0008_workexperience_industry'),
    ]

    operations = [
    ]
