# Generated by Django 5.1.4 on 2024-12-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0008_alter_languagecertificate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagecertificate',
            name='value',
            field=models.CharField(default='', max_length=255, verbose_name='Value'),
            preserve_default=False,
        ),
    ]
