# Generated by Django 5.1.1 on 2024-10-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0008_profile_employment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('employed', 'Employed'), ('unemployed', 'Unemployed')], max_length=50, null=True, verbose_name='Employment Status'),
        ),
    ]
