# Generated by Django 5.1.4 on 2024-12-10 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_account", "0008_alter_profile_scores"),
        ("flex_blob", "0002_filemodel_uploaded_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="avatar2",
        ),
        migrations.RemoveField(
            model_name="avatarfile",
            name="uploaded_by",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="avatar",
        ),
        migrations.RemoveField(
            model_name="certificateandlicenseofflineverificationmethod",
            name="certificate_file",
        ),
        migrations.RemoveField(
            model_name="canadavisa",
            name="citizenship_document",
        ),
        migrations.RemoveField(
            model_name="communicationmethod",
            name="degree_file",
        ),
        migrations.RemoveField(
            model_name="ieemethod",
            name="education_evaluation_document",
        ),
        migrations.RemoveField(
            model_name="employerlettermethod",
            name="employer_letter",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="full_body_image",
        ),
        migrations.RemoveField(
            model_name="offlinemethod",
            name="certificate_file",
        ),
        migrations.RemoveField(
            model_name="paystubsmethod",
            name="paystubs",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="file",
        ),
    ]
