# Generated by Django 5.1.4 on 2024-12-11 07:18

import account.models
import common.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0008_alter_profile_scores'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avatarfile',
            options={'verbose_name': 'Avatar Image', 'verbose_name_plural': 'Avatar Images'},
        ),
        migrations.AlterModelOptions(
            name='canadavisa',
            options={'verbose_name': 'Canada Visa', 'verbose_name_plural': 'Canada Visas'},
        ),
        migrations.AlterField(
            model_name='avatarfile',
            name='uploaded_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='canadavisa',
            name='citizenship_document',
            field=models.FileField(upload_to=account.models.citizenship_document_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png']), common.validators.ValidateFileSize(max=2)], verbose_name='Citizenship Document'),
        ),
        migrations.AlterField(
            model_name='certificateandlicenseofflineverificationmethod',
            name='certificate_file',
            field=models.FileField(upload_to=account.models.certificate_and_license_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png']), common.validators.ValidateFileSize(max=2)], verbose_name='Certificate And License'),
        ),
        migrations.AlterField(
            model_name='communicationmethod',
            name='degree_file',
            field=models.FileField(upload_to=account.models.degree_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png']), common.validators.ValidateFileSize(max=2)], verbose_name='Degree File'),
        ),
        migrations.AlterField(
            model_name='employerlettermethod',
            name='employer_letter',
            field=models.FileField(upload_to=account.models.employer_letter_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png']), common.validators.ValidateFileSize(max=2)], verbose_name='Employer Letter'),
        ),
        migrations.AlterField(
            model_name='ieemethod',
            name='education_evaluation_document',
            field=models.FileField(upload_to=account.models.education_evaluation_document_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png']), common.validators.ValidateFileSize(max=2)], verbose_name='Education Evaluation Document'),
        ),
        migrations.AlterField(
            model_name='offlinemethod',
            name='certificate_file',
            field=models.FileField(upload_to=account.models.language_certificate_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png']), common.validators.ValidateFileSize(max=2)], verbose_name='Language Certificate'),
        ),
        migrations.AlterField(
            model_name='paystubsmethod',
            name='paystubs',
            field=models.FileField(upload_to=account.models.paystubs_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png']), common.validators.ValidateFileSize(max=2)], verbose_name='Employer Letter'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.avatar_path, validators=[common.validators.ValidateFileSize(max=1)], verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_body_image',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.full_body_image_path, validators=[common.validators.ValidateFileSize(max=1)], verbose_name='Full Body Image'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(upload_to=account.models.resume_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png']), common.validators.ValidateFileSize(max=2)], verbose_name='Resume'),
        ),
    ]
