# Generated by Django 5.1.4 on 2023-03-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0009_merge_20241214_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='task_name',
            field=models.CharField(choices=[('find_available_jobs', 'find_available_jobs'), ('set_user_skills', 'set_user_skills'), ('set_user_resume_json', 'set_user_resume_json'), ('send_email_async', 'send_email_async'), ('send_work_experience_verification', 'send_work_experience_verification'), ('auth_async_email', 'auth_async_email')], max_length=255),
        ),
    ]
