# Generated by Django 5.1.4 on 2024-12-11 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0009_alter_avatarfile_options_alter_canadavisa_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar2',
        ),
        migrations.AlterField(
            model_name='ieemethod',
            name='evaluator',
            field=models.CharField(choices=[('wes', 'World Education Services'), ('iqas', 'International Qualifications Assessment Service'), ('icas', 'International Credential Assessment Service of Canada'), ('ces', 'Comparative Education Service'), ('other', 'Other')], max_length=50, verbose_name='Academic Credential Evaluator'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
    ]
