# Generated by Django 5.1.1 on 2024-10-14 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0009_alter_profile_employment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='job',
            new_name='interested_jobs',
        ),
    ]
