# Generated by Django 5.1.4 on 2024-12-08 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0009_languagecertificate_value'),
        ('common', '0008_delete_languageproficiencyresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languagecertificate',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='languagecertificate',
            name='value',
        ),
        migrations.CreateModel(
            name='LanguageCertificateValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('language_certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_account.languagecertificate', verbose_name='Language Certificate')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='common.languageproficiencyskill', verbose_name='Skill')),
            ],
            options={
                'verbose_name': 'Eav Value',
                'verbose_name_plural': 'Eav Values',
                'abstract': False,
            },
        ),
    ]
