# Generated by Django 5.1.4 on 2024-12-10 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0009_remove_profile_avatar2_alter_avatarfile_uploaded_by_and_more'),
        ('flex_blob', '0002_filemodel_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatarfile',
            name='uploaded_by',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='auth_account.avatarfile', verbose_name='Avatar'),
        ),
        migrations.CreateModel(
            name='CertificateFile',
            fields=[
                ('filemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flex_blob.filemodel')),
                ('uploaded_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('flex_blob.filemodel',),
        ),
        migrations.AddField(
            model_name='certificateandlicenseofflineverificationmethod',
            name='certificate_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offline_method', to='auth_account.certificatefile', verbose_name='Certificate And License'),
        ),
        migrations.CreateModel(
            name='CitizenshipDocumentFile',
            fields=[
                ('filemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flex_blob.filemodel')),
                ('uploaded_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('flex_blob.filemodel',),
        ),
        migrations.AddField(
            model_name='canadavisa',
            name='citizenship_document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canada_visa', to='auth_account.citizenshipdocumentfile', verbose_name='Citizenship Document'),
        ),
        migrations.CreateModel(
            name='DegreeFile',
            fields=[
                ('filemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flex_blob.filemodel')),
                ('uploaded_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('flex_blob.filemodel',),
        ),
        migrations.AddField(
            model_name='communicationmethod',
            name='degree_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communication_method', to='auth_account.degreefile', verbose_name='Degree File'),
        ),
        migrations.CreateModel(
            name='EducationEvaluationDocumentFile',
            fields=[
                ('filemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flex_blob.filemodel')),
                ('uploaded_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('flex_blob.filemodel',),
        ),
        migrations.AddField(
            model_name='ieemethod',
            name='education_evaluation_document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iee_method', to='auth_account.educationevaluationdocumentfile', verbose_name='Education Evaluation Document'),
        ),
        migrations.CreateModel(
            name='EmployerLetterFile',
            fields=[
                ('filemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flex_blob.filemodel')),
                ('uploaded_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('flex_blob.filemodel',),
        ),
        migrations.AddField(
            model_name='employerlettermethod',
            name='employer_letter',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employer_letter_method', to='auth_account.employerletterfile', verbose_name='Employer Letter'),
        ),
        migrations.CreateModel(
            name='FullBodyImageFile',
            fields=[
                ('filemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flex_blob.filemodel')),
                ('uploaded_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('flex_blob.filemodel',),
        ),
        migrations.AddField(
            model_name='profile',
            name='full_body_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='auth_account.fullbodyimagefile', verbose_name='Full Body Image'),
        ),
        migrations.CreateModel(
            name='LanguageCertificateFile',
            fields=[
                ('filemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flex_blob.filemodel')),
                ('uploaded_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('flex_blob.filemodel',),
        ),
        migrations.AddField(
            model_name='offlinemethod',
            name='certificate_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offline_method', to='auth_account.languagecertificatefile', verbose_name='Language Certificate'),
        ),
        migrations.CreateModel(
            name='PaystubsFile',
            fields=[
                ('filemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flex_blob.filemodel')),
                ('uploaded_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('flex_blob.filemodel',),
        ),
        migrations.AddField(
            model_name='paystubsmethod',
            name='paystubs',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paystubs_method', to='auth_account.paystubsfile', verbose_name='Employer Letter'),
        ),
        migrations.CreateModel(
            name='ResumeFile',
            fields=[
                ('filemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flex_blob.filemodel')),
                ('uploaded_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('flex_blob.filemodel',),
        ),
        migrations.AddField(
            model_name='resume',
            name='file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='auth_account.resumefile', verbose_name='Resume'),
        ),
    ]
