# Generated by Django 5.1.1 on 2024-10-09 17:12

import account.models
import common.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_field_university_website'),
        ('cpj_account', '0009_field_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.field', verbose_name='Field'),
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', account.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(choices=[('bachelors', 'Bachelors'), ('masters', 'Masters'), ('phd', 'PhD'), ('associate', 'Associate'), ('diploma', 'Diploma'), ('certificate', 'Certificate')], max_length=50, verbose_name='Degree'),
        ),
        migrations.AlterField(
            model_name='education',
            name='status',
            field=models.CharField(choices=[('verified', 'Verified'), ('rejected', 'Rejected'), ('pending', 'Pending'), ('draft', 'Draft')], default='pending', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='full_body_image',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.full_body_image_path, validators=[common.validators.ValidateFileSize(max=3)], verbose_name='Full Body Image'),
        ),
        migrations.CreateModel(
            name='EducationVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('international_education_evaluation', 'International Education Evaluation'), ('communication', 'Communication'), ('self_verification', 'Self Verification')], max_length=50, verbose_name='Verification Method')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is Verified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpj_account.education', verbose_name='Education')),
            ],
            options={
                'verbose_name': 'Education Verification',
                'verbose_name_plural': 'Education Verifications',
            },
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('department', models.CharField(max_length=255, verbose_name='Department')),
                ('person', models.CharField(max_length=255, verbose_name='Person')),
                ('degree_file', models.FileField(upload_to=account.models.degree_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png']), common.validators.ValidateFileSize(max=5)], verbose_name='Degree File')),
                ('education_verification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cpj_account.educationverification', verbose_name='Education Verification')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InternationalEducationEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ices_document', models.FileField(upload_to=account.models.ices_document_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png']), common.validators.ValidateFileSize(max=5)], verbose_name='ICES Document')),
                ('citizen_document', models.FileField(upload_to=account.models.citizen_document_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png']), common.validators.ValidateFileSize(max=5)], verbose_name='Citizen Document')),
                ('evaluator', models.CharField(choices=[('wes', 'World Education Services'), ('iqas', 'International Qualifications Assessment Service'), ('icas', 'International Credential Assessment Service of Canada'), ('ces', 'Comparative Education Service')], max_length=50, verbose_name='Academic Credential Evaluator')),
                ('education_verification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cpj_account.educationverification', verbose_name='Education Verification')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Field',
        ),
    ]
