# Generated by Django 5.1.1 on 2024-10-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0010_rename_job_profile_interested_jobs'),
        ('common', '0003_field_university_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interested_jobs',
            field=models.ManyToManyField(blank=True, to='common.job', verbose_name='Interested Jobs'),
        ),
    ]
