# Generated by Django 5.1.4 on 2024-12-10 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0010_avatarfile_uploaded_by_profile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avatarfile',
            options={'verbose_name': 'Avatar Image', 'verbose_name_plural': 'Avatar Images'},
        ),
        migrations.AlterModelOptions(
            name='certificatefile',
            options={'verbose_name': 'Certificate File', 'verbose_name_plural': 'Certificate Files'},
        ),
        migrations.AlterModelOptions(
            name='citizenshipdocumentfile',
            options={'verbose_name': 'Citizenship Document File', 'verbose_name_plural': 'Citizenship Document Files'},
        ),
        migrations.AlterModelOptions(
            name='degreefile',
            options={'verbose_name': 'Degree File', 'verbose_name_plural': 'Degree Files'},
        ),
        migrations.AlterModelOptions(
            name='educationevaluationdocumentfile',
            options={'verbose_name': 'Education Evaluation Document File', 'verbose_name_plural': 'Education Evaluation Document Files'},
        ),
        migrations.AlterModelOptions(
            name='employerletterfile',
            options={'verbose_name': 'Employer Letter File', 'verbose_name_plural': 'Employer Letter Files'},
        ),
        migrations.AlterModelOptions(
            name='fullbodyimagefile',
            options={'verbose_name': 'Full Body Image', 'verbose_name_plural': 'Full Body Images'},
        ),
        migrations.AlterModelOptions(
            name='languagecertificatefile',
            options={'verbose_name': 'Language Certificate File', 'verbose_name_plural': 'Language Certificate Files'},
        ),
        migrations.AlterModelOptions(
            name='paystubsfile',
            options={'verbose_name': 'Paystubs File', 'verbose_name_plural': 'Paystubs Files'},
        ),
        migrations.AlterModelOptions(
            name='resumefile',
            options={'verbose_name': 'Resume File', 'verbose_name_plural': 'Resume Files'},
        ),
        migrations.AlterField(
            model_name='canadavisa',
            name='citizenship_document',
            field=models.OneToOneField(default=13, on_delete=django.db.models.deletion.CASCADE, related_name='canada_visa', to='auth_account.citizenshipdocumentfile', verbose_name='Citizenship Document'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificateandlicenseofflineverificationmethod',
            name='certificate_file',
            field=models.OneToOneField(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='offline_method', to='auth_account.certificatefile', verbose_name='Certificate And License'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='communicationmethod',
            name='degree_file',
            field=models.OneToOneField(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='communication_method', to='auth_account.degreefile', verbose_name='Degree File'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employerlettermethod',
            name='employer_letter',
            field=models.OneToOneField(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='employer_letter_method', to='auth_account.employerletterfile', verbose_name='Employer Letter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ieemethod',
            name='education_evaluation_document',
            field=models.OneToOneField(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='iee_method', to='auth_account.educationevaluationdocumentfile', verbose_name='Education Evaluation Document'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offlinemethod',
            name='certificate_file',
            field=models.OneToOneField(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='offline_method', to='auth_account.languagecertificatefile', verbose_name='Language Certificate'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paystubsmethod',
            name='paystubs',
            field=models.OneToOneField(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='paystubs_method', to='auth_account.paystubsfile', verbose_name='Employer Letter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.OneToOneField(default=14, on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='auth_account.resumefile', verbose_name='Resume'),
            preserve_default=False,
        ),
    ]
