# Generated by Django 5.1.4 on 2023-03-29 08:19

import account.choices
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0010_alter_usertask_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='status',
            field=models.CharField(blank=True, choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=50, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='task_name',
            field=models.CharField(choices=account.choices.get_task_names_choices, max_length=255, verbose_name='Task Name'),
        ),
    ]
