# Generated by Django 5.1.4 on 2024-12-08 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0010_remove_languagecertificate_skill_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='languagecertificate',
            options={'verbose_name': 'Language Certificate', 'verbose_name_plural': 'Language Certificates'},
        ),
        migrations.AlterModelOptions(
            name='languagecertificatevalue',
            options={'verbose_name': 'Language Certificate Value', 'verbose_name_plural': 'Language Certificate Values'},
        ),
    ]
