# Generated by Django 5.1.1 on 2024-10-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpj_account', '0010_alter_education_field_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Communication',
            new_name='CommunicationMethod',
        ),
        migrations.RenameModel(
            old_name='InternationalEducationEvaluation',
            new_name='IEEMethod',
        ),
        migrations.AlterField(
            model_name='educationverification',
            name='method',
            field=models.CharField(choices=[('iee', 'International Education Evaluation'), ('communication', 'Communication'), ('self_verification', 'Self Verification')], max_length=50, verbose_name='Verification Method'),
        ),
    ]
