# Generated by Django 5.1.1 on 2024-10-16 12:47

import colorfield.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0011_alter_profile_interested_jobs'),
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('common', '0004_language_languageproficiencytest_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='eye_color',
            field=colorfield.fields.ColorField(blank=True, choices=[('#FFBF00', 'Amber'), ('#5DADEC', 'Blue'), ('#6B4226', 'Brown'), ('#BEBEBE', 'Gray'), ('#1CAC78', 'Green'), ('#8E7618', 'Hazel')], default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='Eye Color'),
        ),
        migrations.CreateModel(
            name='CertificateAndLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('certifier', models.CharField(max_length=255, verbose_name='Certifier')),
                ('issued_at', models.DateField(verbose_name='Issued At')),
                ('expired_at', models.DateField(blank=True, null=True, verbose_name='Expired At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='certificate_and_licenses', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Certificate And License',
                'verbose_name_plural': 'Certificates And Licenses',
            },
        ),
        migrations.CreateModel(
            name='LanguageCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateField(verbose_name='Issued At')),
                ('expired_at', models.DateField(verbose_name='Expired At')),
                ('listening_score', models.FloatField(verbose_name='Listening Score')),
                ('reading_score', models.FloatField(verbose_name='Reading Score')),
                ('writing_score', models.FloatField(verbose_name='Writing Score')),
                ('speaking_score', models.FloatField(verbose_name='Speaking Score')),
                ('band_score', models.FloatField(verbose_name='Band Score')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='common.language', verbose_name='Language')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='common.languageproficiencytest', verbose_name='Test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='language_certificates', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Language Certificate',
                'verbose_name_plural': 'Language Certificates',
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.ManyToManyField(related_name='users', to='common.skill', verbose_name='Skills')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='skills', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Skill',
                'verbose_name_plural': 'User Skills',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(verbose_name='Start Date')),
                ('end', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('organization', models.CharField(max_length=255, verbose_name='Organization')),
                ('status', models.CharField(choices=[('submited', 'Submited'), ('draft', 'Draft')], max_length=50, verbose_name='Status')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='cities_light.city', verbose_name='City')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='common.job', verbose_name='Job')),
                ('skills', models.ManyToManyField(related_name='work_experiences', to='common.skill', verbose_name='Skills')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='work_experiences', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Work Experience',
                'verbose_name_plural': 'Work Experiences',
            },
        ),
    ]
