# Generated by Django 5.1.4 on 2024-12-08 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0011_alter_languagecertificate_options_and_more'),
        ('common', '0010_alter_languageproficiencyskill_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagecertificate',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='common.languageproficiencytest', verbose_name='Test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='languagecertificatevalue',
            name='language_certificate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='auth_account.languagecertificate', verbose_name='Language Certificate'),
        ),
    ]
