# Generated by Django 5.1.4 on 2024-12-10 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0011_alter_avatarfile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='canadavisa',
            options={'verbose_name': 'Canada Visa', 'verbose_name_plural': 'Canada Visas'},
        ),
        migrations.AlterField(
            model_name='canadavisa',
            name='citizenship_document',
            field=models.OneToOneField(default=13, on_delete=django.db.models.deletion.CASCADE, related_name='canada_visa', to='auth_account.citizenshipdocumentfile', verbose_name='Citizenship Document'),
        ),
    ]
