# Generated by Django 5.1.4 on 2023-04-01 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0011_alter_usertask_status_alter_usertask_task_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificateandlicense',
            options={'ordering': ['issued_at'], 'verbose_name': 'Certificate And License', 'verbose_name_plural': 'Certificates And Licenses'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['end', 'start'], 'verbose_name': 'Education', 'verbose_name_plural': 'Educations'},
        ),
        migrations.AlterModelOptions(
            name='workexperience',
            options={'ordering': ['end', 'start'], 'verbose_name': 'Work Experience', 'verbose_name_plural': 'Work Experiences'},
        ),
    ]
