# Generated by Django 5.1.4 on 2024-12-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0011_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='resume_json',
            field=models.JSONField(default=dict, editable=False, verbose_name='Resume JSON'),
        ),
    ]
