# Generated by Django 5.1.1 on 2024-10-16 15:56

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0012_alter_profile_eye_color_certificateandlicense_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='skin_color',
            field=colorfield.fields.ColorField(blank=True, choices=[('#FFDFC4', 'Very Fair'), ('#F0D5B1', 'Fair'), ('#E5B897', 'Light'), ('#D9A377', 'Light Medium'), ('#C68642', 'Medium'), ('#A86B33', 'Olive'), ('#8D5524', 'Brown'), ('#60391C', 'Dark Brown'), ('#3B260B', 'Very Dark'), ('#100C08', 'Deep')], default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='Skin Color'),
        ),
    ]
