# Generated by Django 5.1.4 on 2024-12-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0012_languagecertificate_test_and_more'),
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='job_city',
        ),
        migrations.AddField(
            model_name='profile',
            name='job_city',
            field=models.ManyToManyField(related_name='job_profiles', to='cities_light.city', verbose_name='Job City'),
        ),
    ]
