# Generated by Django 5.1.4 on 2024-12-16 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_account", "0012_alter_certificateandlicense_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="score",
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name="Score"),
        ),
        migrations.RemoveField(
            model_name="profile",
            name="scores",
            field=models.JSONField(default=dict, verbose_name="Scores"),
        ),
        migrations.AddField(
            model_name="profile",
            name="scores",
            field=models.JSONField(default=dict, verbose_name="Scores"),
        ),
    ]
