# Generated by Django 5.1.1 on 2024-10-17 16:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0013_alter_profile_skin_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='communicationmethod',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='communicationmethod',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Verified At'),
        ),
        migrations.AddField(
            model_name='education',
            name='allow_self_verification',
            field=models.BooleanField(default=False, verbose_name='Allow Self Verification'),
        ),
        migrations.AddField(
            model_name='education',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Verified At'),
        ),
        migrations.AddField(
            model_name='ieemethod',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ieemethod',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Verified At'),
        ),
        migrations.AlterField(
            model_name='education',
            name='method',
            field=models.CharField(choices=[('iee', 'International Education Evaluation'), ('communication', 'Communication')], max_length=50, verbose_name='Verification Method'),
        ),
        migrations.AlterField(
            model_name='education',
            name='status',
            field=models.CharField(choices=[('drafted', 'Drafted'), ('submitted', 'Submitted'), ('rejected', 'Rejected'), ('verified', 'Verified'), ('self_verified', 'Self Verified')], default='drafted', max_length=50, verbose_name='Status'),
        ),
    ]
