# Generated by Django 5.1.4 on 2024-12-08 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0013_remove_profile_job_city_profile_job_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='job_city',
            new_name='job_cities',
        ),
    ]
