# Generated by Django 5.1.1 on 2024-12-12 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0013_usertask'),
        ('flex_blob', '0002_filemodel_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_x',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_x', to='auth_account.avatarfile', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='avatarfile',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CertificateFile',
            fields=[
                ('filemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flex_blob.filemodel')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificate File',
                'verbose_name_plural': 'Certificate Files',
            },
            bases=('flex_blob.filemodel',),
        ),
        migrations.AddField(
            model_name='certificateandlicenseofflineverificationmethod',
            name='certificate_file_x',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offline_method_x', to='auth_account.certificatefile', verbose_name='Certificate And License'),
        ),
        migrations.CreateModel(
            name='CitizenshipDocumentFile',
            fields=[
                ('filemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flex_blob.filemodel')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Citizenship Document File',
                'verbose_name_plural': 'Citizenship Document Files',
            },
            bases=('flex_blob.filemodel',),
        ),
        migrations.AddField(
            model_name='canadavisa',
            name='citizenship_document_x',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canada_visa_x', to='auth_account.citizenshipdocumentfile', verbose_name='Citizenship Document'),
        ),
        migrations.CreateModel(
            name='DegreeFile',
            fields=[
                ('filemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flex_blob.filemodel')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Degree File',
                'verbose_name_plural': 'Degree Files',
            },
            bases=('flex_blob.filemodel',),
        ),
        migrations.AddField(
            model_name='communicationmethod',
            name='degree_file_x',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communication_method_x', to='auth_account.degreefile', verbose_name='Degree File'),
        ),
        migrations.CreateModel(
            name='EducationEvaluationDocumentFile',
            fields=[
                ('filemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flex_blob.filemodel')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Education Evaluation Document File',
                'verbose_name_plural': 'Education Evaluation Document Files',
            },
            bases=('flex_blob.filemodel',),
        ),
        migrations.AddField(
            model_name='ieemethod',
            name='education_evaluation_document_x',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iee_method_x', to='auth_account.educationevaluationdocumentfile', verbose_name='Education Evaluation Document'),
        ),
        migrations.CreateModel(
            name='EmployerLetterFile',
            fields=[
                ('filemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flex_blob.filemodel')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employer Letter File',
                'verbose_name_plural': 'Employer Letter Files',
            },
            bases=('flex_blob.filemodel',),
        ),
        migrations.AddField(
            model_name='employerlettermethod',
            name='employer_letter_x',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employer_letter_method_x', to='auth_account.employerletterfile', verbose_name='Employer Letter'),
        ),
        migrations.CreateModel(
            name='FullBodyImageFile',
            fields=[
                ('filemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flex_blob.filemodel')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Full Body Image',
                'verbose_name_plural': 'Full Body Images',
            },
            bases=('flex_blob.filemodel',),
        ),
        migrations.AddField(
            model_name='profile',
            name='full_body_image_x',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_x', to='auth_account.fullbodyimagefile', verbose_name='Full Body Image'),
        ),
        migrations.CreateModel(
            name='LanguageCertificateFile',
            fields=[
                ('filemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flex_blob.filemodel')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Language Certificate File',
                'verbose_name_plural': 'Language Certificate Files',
            },
            bases=('flex_blob.filemodel',),
        ),
        migrations.AddField(
            model_name='offlinemethod',
            name='certificate_file_x',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offline_method_x', to='auth_account.languagecertificatefile', verbose_name='Language Certificate'),
        ),
        migrations.CreateModel(
            name='PaystubsFile',
            fields=[
                ('filemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flex_blob.filemodel')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paystubs File',
                'verbose_name_plural': 'Paystubs Files',
            },
            bases=('flex_blob.filemodel',),
        ),
        migrations.AddField(
            model_name='paystubsmethod',
            name='paystubs_x',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paystubs_method_x', to='auth_account.paystubsfile', verbose_name='Paystubs'),
        ),
        migrations.CreateModel(
            name='ResumeFile',
            fields=[
                ('filemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flex_blob.filemodel')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resume File',
                'verbose_name_plural': 'Resume Files',
            },
            bases=('flex_blob.filemodel',),
        ),
        migrations.AddField(
            model_name='resume',
            name='file_x',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resume_x', to='auth_account.resumefile', verbose_name='Resume'),
        ),
    ]
