# Generated by Django 5.1.4 on 2023-04-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0013_profile_score_alter_profile_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='score',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='scores',
            field=models.JSONField(blank=True, default=dict, verbose_name='Scores'),
        ),
    ]
