# Generated by Django 5.1.2 on 2024-10-18 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0014_remove_education_is_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='method',
        ),
    ]
