# Generated by Django 5.1.1 on 2024-10-18 14:16

import account.models
import common.validators
import datetime
import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0014_remove_education_is_verified_and_more'),
        ('common', '0006_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='allow_self_verification',
            field=models.BooleanField(default=False, verbose_name='Allow Self Verification'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 10, 18, 14, 16, 37, 671422, tzinfo=datetime.timezone.utc), verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workexperience',
            name='method',
            field=models.CharField(blank=True, choices=[('employer_letter', 'Employer Letter'), ('paystubs', 'Paystubs')], max_length=50, null=True, verbose_name='Verification Method'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Verified At'),
        ),
        migrations.AlterField(
            model_name='education',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='status',
            field=models.CharField(choices=[('drafted', 'Drafted'), ('submitted', 'Submitted'), ('rejected', 'Rejected'), ('verified', 'Verified'), ('self_verified', 'Self Verified')], default='drafted', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.CreateModel(
            name='EmployerLetterMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('employer_letter', models.FileField(upload_to=account.models.employer_letter_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png']), common.validators.ValidateFileSize(max=5)], verbose_name='Employer Letter')),
                ('work_experience', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth_account.workexperience', verbose_name='Work Experience')),
            ],
            options={
                'verbose_name': 'Employer Letter Method',
                'verbose_name_plural': 'Employer Letter Methods',
            },
        ),
        migrations.CreateModel(
            name='PaystubsMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('paystubs', models.FileField(upload_to=account.models.paystubs_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png']), common.validators.ValidateFileSize(max=5)], verbose_name='Employer Letter')),
                ('work_experience', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth_account.workexperience', verbose_name='Work Experience')),
            ],
            options={
                'verbose_name': 'Paystubs Method',
                'verbose_name_plural': 'Paystubs Methods',
            },
        ),
        migrations.CreateModel(
            name='ReferenceCheckEmployer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_nubmer', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone Number')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.position', verbose_name='Position')),
                ('work_experience_verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_account.employerlettermethod', verbose_name='Work Experience Verification')),
            ],
        ),
    ]
