# Generated by Django 5.1.4 on 2024-12-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0014_profile_avatar_x_alter_avatarfile_uploaded_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume_json',
            field=models.JSONField(default=dict, verbose_name='Resume JSON'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Resume Text'),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='scheduled', max_length=50),
        ),
    ]
