# Generated by Django 5.1.4 on 2024-12-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0015_alter_usertask_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume_json',
            field=models.JSONField(default=dict, verbose_name='Resume JSON'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Resume Text'),
        ),
    ]
