# Generated by Django 5.1.4 on 2024-12-12 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0015_alter_resume_resume_json_alter_resume_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='file_x',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resume_x', to='auth_account.resumefile', verbose_name='Resume'),
        ),
    ]
