# Generated by Django 5.1.1 on 2023-04-19 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0015_organization_position'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='organization',
            name='business_type',
            field=models.CharField(blank=True, choices=[('software', 'Software'), ('service', 'Service'), ('product', 'Product')], max_length=50, null=True, verbose_name='Business Type'),
        ),
        migrations.AddField(
            model_name='organization',
            name='established_at',
            field=models.DateField(blank=True, null=True, verbose_name='Established At'),
        ),
        migrations.AddField(
            model_name='organization',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='common.industry', verbose_name='Industry'),
        ),
        migrations.AddField(
            model_name='organization',
            name='national_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='National Number'),
        ),
        migrations.AddField(
            model_name='organization',
            name='short_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Short Name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='size',
            field=models.CharField(blank=True, choices=[('_1_10', '1-10'), ('_10_50', '10-50'), ('_50_100', '50-100'), ('_100_500', '100-500'), ('_500_1000', '500-1000'), ('over_1000', 'Over 1000')], max_length=50, null=True, verbose_name='Size'),
        ),
        migrations.AddField(
            model_name='organization',
            name='type',
            field=models.CharField(blank=True, choices=[('company', 'Company'), ('stock', 'Stock'), ('non_profit', 'Non-Profit'), ('government', 'Government'), ('educational', 'Educational'), ('other', 'Other')], max_length=50, null=True, verbose_name='Type'),
        ),
    ]
