# Generated by Django 5.1.2 on 2024-10-18 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0015_remove_education_method'),
        ('auth_account', '0015_workexperience_allow_self_verification_and_more'),
    ]

    operations = [
    ]
