# Generated by Django 5.1.4 on 2023-04-19 17:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0016_organization_about_organization_business_type_and_more'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='available_jobs',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='common.job', verbose_name='Available Jobs'),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Birth Date'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('not_known', 'Not Known'), ('not_applicable', 'Not Applicable')], max_length=50, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='profile',
            name='raw_skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, null=True, size=None, verbose_name='Raw Skills'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(editable=False, related_name='profiles', to='common.skill', verbose_name='Skills'),
        ),
    ]
