# Generated by Django 5.1.4 on 2024-12-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0016_alter_resume_file_x'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='task_name',
            field=models.CharField(choices=[], max_length=255),
        ),
    ]
