# Generated by Django 5.1.1 on 2024-10-21 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0016_merge_20241018_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referencecheckemployer',
            options={'verbose_name': 'Reference Check Employer', 'verbose_name_plural': 'Reference Check Employers'},
        ),
        migrations.AddField(
            model_name='employerlettermethod',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Verified At'),
        ),
        migrations.AddField(
            model_name='paystubsmethod',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Verified At'),
        ),
        migrations.AlterField(
            model_name='education',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
