# Generated by Django 5.1.1 on 2024-10-21 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0017_alter_referencecheckemployer_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperience',
            name='method',
        ),
    ]
