# Generated by Django 5.1.1 on 2024-12-13 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0017_alter_usertask_task_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canadavisa',
            name='citizenship_document',
        ),
        migrations.RemoveField(
            model_name='certificateandlicenseofflineverificationmethod',
            name='certificate_file',
        ),
        migrations.RemoveField(
            model_name='communicationmethod',
            name='degree_file',
        ),
        migrations.RemoveField(
            model_name='employerlettermethod',
            name='employer_letter',
        ),
        migrations.RemoveField(
            model_name='ieemethod',
            name='education_evaluation_document',
        ),
        migrations.RemoveField(
            model_name='offlinemethod',
            name='certificate_file',
        ),
        migrations.RemoveField(
            model_name='paystubsmethod',
            name='paystubs',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='full_body_image',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='file',
        ),
    ]
