# Generated by Django 5.1.1 on 2024-12-13 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0018_remove_canadavisa_citizenship_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canadavisa',
            name='citizenship_document_x',
        ),
        migrations.RemoveField(
            model_name='certificateandlicenseofflineverificationmethod',
            name='certificate_file_x',
        ),
        migrations.RemoveField(
            model_name='communicationmethod',
            name='degree_file_x',
        ),
        migrations.RemoveField(
            model_name='employerlettermethod',
            name='employer_letter_x',
        ),
        migrations.RemoveField(
            model_name='ieemethod',
            name='education_evaluation_document_x',
        ),
        migrations.RemoveField(
            model_name='offlinemethod',
            name='certificate_file_x',
        ),
        migrations.RemoveField(
            model_name='paystubsmethod',
            name='paystubs_x',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='avatar_x',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='full_body_image_x',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='file_x',
        ),
        migrations.AddField(
            model_name='canadavisa',
            name='citizenship_document',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canada_visa', to='auth_account.citizenshipdocumentfile', verbose_name='Citizenship Document'),
        ),
        migrations.AddField(
            model_name='certificateandlicenseofflineverificationmethod',
            name='certificate_file',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offline_method', to='auth_account.certificatefile', verbose_name='Certificate And License'),
        ),
        migrations.AddField(
            model_name='communicationmethod',
            name='degree_file',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communication_method', to='auth_account.degreefile', verbose_name='Degree File'),
        ),
        migrations.AddField(
            model_name='employerlettermethod',
            name='employer_letter',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employer_letter_method', to='auth_account.employerletterfile', verbose_name='Employer Letter'),
        ),
        migrations.AddField(
            model_name='ieemethod',
            name='education_evaluation_document',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iee_method', to='auth_account.educationevaluationdocumentfile', verbose_name='Education Evaluation Document'),
        ),
        migrations.AddField(
            model_name='offlinemethod',
            name='certificate_file',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offline_method', to='auth_account.languagecertificatefile', verbose_name='Language Certificate'),
        ),
        migrations.AddField(
            model_name='paystubsmethod',
            name='paystubs',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paystubs_method', to='auth_account.paystubsfile', verbose_name='Paystubs'),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='auth_account.avatarfile', verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='profile',
            name='full_body_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='auth_account.fullbodyimagefile', verbose_name='Full Body Image'),
        ),
        migrations.AddField(
            model_name='resume',
            name='file',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='auth_account.resumefile', verbose_name='Resume'),
        ),
    ]
