# Generated by Django 5.1.4 on 2024-12-18 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0018_convert_user_to_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Contactable',
                'verbose_name_plural': 'Contactables',
            },
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='contact',
            name='contactable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='auth_account.contactable', verbose_name='Contactable'),
        ),
        migrations.AddField(
            model_name='organization',
            name='contactable',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_account.contactable', verbose_name='Contactable'),
        ),
        migrations.AddField(
            model_name='profile',
            name='contactable',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_account.contactable', verbose_name='Contactable'),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('contactable', 'type')},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
    ]
