# Generated by Django 5.1.1 on 2024-10-21 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0018_remove_workexperience_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referencecheckemployer',
            old_name='phone_nubmer',
            new_name='phone_number',
        ),
    ]
