# Generated by Django 5.1.1 on 2024-10-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0019_rename_phone_nubmer_referencecheckemployer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagecertificate',
            name='status',
            field=models.CharField(choices=[('drafted', 'Drafted'), ('submitted', 'Submitted')], default='drafted', max_length=50, verbose_name='Status'),
        ),
    ]
