# Generated by Django 5.1.4 on 2024-12-13 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0019_remove_canadavisa_citizenship_document_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canadavisa',
            name='citizenship_document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='canada_visa', to='auth_account.citizenshipdocumentfile', verbose_name='Citizenship Document'),
        ),
        migrations.AlterField(
            model_name='certificateandlicenseofflineverificationmethod',
            name='certificate_file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offline_method', to='auth_account.certificatefile', verbose_name='Certificate And License'),
        ),
        migrations.AlterField(
            model_name='communicationmethod',
            name='degree_file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='communication_method', to='auth_account.degreefile', verbose_name='Degree File'),
        ),
        migrations.AlterField(
            model_name='employerlettermethod',
            name='employer_letter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_letter_method', to='auth_account.employerletterfile', verbose_name='Employer Letter'),
        ),
        migrations.AlterField(
            model_name='ieemethod',
            name='education_evaluation_document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='iee_method', to='auth_account.educationevaluationdocumentfile', verbose_name='Education Evaluation Document'),
        ),
        migrations.AlterField(
            model_name='offlinemethod',
            name='certificate_file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offline_method', to='auth_account.languagecertificatefile', verbose_name='Language Certificate'),
        ),
        migrations.AlterField(
            model_name='paystubsmethod',
            name='paystubs',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paystubs_method', to='auth_account.paystubsfile', verbose_name='Paystubs'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='auth_account.resumefile', verbose_name='Resume'),
        ),
    ]
