# Generated by Django 5.1.1 on 2024-10-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0020_languagecertificate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateandlicense',
            name='status',
            field=models.CharField(choices=[('drafted', 'Drafted'), ('submitted', 'Submitted')], default='drafted', max_length=50, verbose_name='Status'),
        ),
    ]
