# Generated by Django 5.1.4 on 2024-12-18 19:34

import account.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0020_alter_profile_contactable'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='contactable',
            field=models.OneToOneField(default=account.models.contactable_default, on_delete=django.db.models.deletion.CASCADE, to='auth_account.contactable', verbose_name='Contactable'),
        ),
    ]
