# Generated by Django 5.1.1 on 2024-10-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0021_certificateandlicense_status'),
        ('common', '0006_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(related_name='users', to='common.skill', verbose_name='Skills'),
        ),
        migrations.DeleteModel(
            name='UserSkill',
        ),
    ]
