# Generated by Django 5.1.4 on 2023-04-18 15:07

from django.db import migrations


def copy_to_contactables(apps, schema_editor):
    Contact = apps.get_model("auth_account", "Contact")
    Contactable = apps.get_model("auth_account", "Contactable")
    Profile = apps.get_model("auth_account", "Profile")

    for contact in Contact.objects.filter(user__isnull=False):
        user = contact.user
        if not (profile := getattr(user, "profile", None)):
            profile = Profile.objects.create(user=user)

        if not (contactable := getattr(profile, "contactable", None)):
            contactable = Contactable.objects.create()

        contact.contactable = contactable
        contact.save()


def reverse_copy_to_contactables(apps, schema_editor):
    Contact = apps.get_model("auth_account", "Contact")
    for contact in Contact.objects.filter(contactable__isnull=False):
        contact.user = contact.contactable.profile.user
        contact.save()


class Migration(migrations.Migration):
    dependencies = [
        ("auth_account", "0021_contact_user_alter_organization_contactable"),
    ]

    operations = [
        migrations.RunPython(copy_to_contactables, reverse_copy_to_contactables),
    ]
