# Generated by Django 5.1.4 on 2024-12-18 15:07

from django.db import migrations


def copy_to_contactables(apps, schema_editor):
    Contact = apps.get_model("auth_account", "Contact")
    Profile = apps.get_model("auth_account", "Profile")

    for contact in Contact.objects.all():
        user = contact.user
        if not (profile := user.get_profile()):
            profile = Profile.objects.create(user=user)

        contact.contactable = profile.contactable
        contact.save()


def reverse_copy_to_contactables(apps, schema_editor):
    Contact = apps.get_model("auth_account", "Contact")
    for contact in Contact.objects.all():
        contact.user = contact.contactable.profile.user
        contact.save()


class Migration(migrations.Migration):
    dependencies = [
        ("auth_account", "0021_contact_user_alter_organization_contactable"),
    ]

    operations = [
        migrations.RunPython(copy_to_contactables, reverse_copy_to_contactables),
    ]
