# Generated by Django 5.1.4 on 2024-12-19 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0022_convert_contactables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='contactable',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_account.contactable', verbose_name='Contactable'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contactable',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_account.contactable', verbose_name='Contactable'),
        ),
    ]
