# Generated by Django 5.1.1 on 2024-10-23 13:46

import account.models
import common.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0022_user_skills_delete_userskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagecertificate',
            name='allow_self_verification',
            field=models.BooleanField(default=False, verbose_name='Allow Self Verification'),
        ),
        migrations.AddField(
            model_name='languagecertificate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='languagecertificate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='languagecertificate',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Verified At'),
        ),
        migrations.AlterField(
            model_name='languagecertificate',
            name='status',
            field=models.CharField(choices=[('drafted', 'Drafted'), ('submitted', 'Submitted'), ('rejected', 'Rejected'), ('verified', 'Verified'), ('self_verified', 'Self Verified')], default='drafted', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='languagecertificate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.CreateModel(
            name='OfflineMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verified At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('certificate_file', models.FileField(upload_to=account.models.language_certificate_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png']), common.validators.ValidateFileSize(max=5)], verbose_name='Language Certificate')),
                ('language_certificate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth_account.languagecertificate', verbose_name='Language Certificate')),
            ],
            options={
                'verbose_name': 'Offline Method',
                'verbose_name_plural': 'Offline Methods',
            },
        ),
        migrations.CreateModel(
            name='OnlineMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verified At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('certificate_link', models.URLField(verbose_name='Link')),
                ('language_certificate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth_account.languagecertificate', verbose_name='Language Certificate')),
            ],
            options={
                'verbose_name': 'Online Method',
                'verbose_name_plural': 'Online Methods',
            },
        ),
    ]
