# Generated by Django 5.1.1 on 2023-04-27 13:37

import account.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0022_convert_contactables'),
        ('flex_blob', '0002_filemodel_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OrganizationInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('role', models.CharField(choices=[('cto', 'CTO'), ('cfo', 'CFO'), ('ceo', 'CEO'), ('hr', 'HR'), ('operations', 'Operations'), ('associate', 'Associate'), ('other', 'Other'), ('creator', 'Creator')], default='other', max_length=50, verbose_name='Role')),
                ('token', models.CharField(db_index=True, default=account.models.generate_invitation_token, max_length=15, unique=True, verbose_name='Token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_account.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Organization Invitation',
                'verbose_name_plural': 'Organization Invitations',
            },
        ),
        migrations.CreateModel(
            name='OrganizationLogoFile',
            fields=[
                ('filemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flex_blob.filemodel')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization Logo File',
                'verbose_name_plural': 'Organization Logo Files',
            },
            bases=('flex_blob.filemodel',),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization', to='auth_account.organizationlogofile', verbose_name='Logo'),
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('cto', 'CTO'), ('cfo', 'CFO'), ('ceo', 'CEO'), ('hr', 'HR'), ('operations', 'Operations'), ('associate', 'Associate'), ('other', 'Other'), ('creator', 'Creator')], default='other', max_length=50, verbose_name='Role')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='invited_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Invited By')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='auth_account.organization', verbose_name='Organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Organization Membership',
                'verbose_name_plural': 'Organization Memberships',
            },
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
