# Generated by Django 5.1.1 on 2024-10-24 08:27

import account.models
import common.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0023_languagecertificate_allow_self_verification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateandlicense',
            name='allow_self_verification',
            field=models.BooleanField(default=False, verbose_name='Allow Self Verification'),
        ),
        migrations.AddField(
            model_name='certificateandlicense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificateandlicense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='certificateandlicense',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Verified At'),
        ),
        migrations.AlterField(
            model_name='certificateandlicense',
            name='status',
            field=models.CharField(choices=[('drafted', 'Drafted'), ('submitted', 'Submitted'), ('rejected', 'Rejected'), ('verified', 'Verified'), ('self_verified', 'Self Verified')], default='drafted', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='certificateandlicense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.CreateModel(
            name='CertificateAndLicenseVerificationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verified At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('certificate_link', models.URLField(blank=True, null=True, verbose_name='Link')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to=account.models.certificate_and_license_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png']), common.validators.ValidateFileSize(max=5)], verbose_name='Certificate And License')),
                ('certificate_and_license', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth_account.certificateandlicense', verbose_name='Certificate And License')),
            ],
            options={
                'verbose_name': 'Certificate And License Verification Method',
                'verbose_name_plural': 'Certificate And License Verification Methods',
            },
        ),
    ]
