# Generated by Django 5.1.1 on 2024-12-19 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0023_alter_organization_contactable_and_more'),
        ('auth_account', '0023_organization_created_by_organizationinvitation_and_more'),
    ]

    operations = [
    ]
