# Generated by Django 5.1.1 on 2024-10-24 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0024_certificateandlicense_allow_self_verification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencecheckemployer',
            name='work_experience_verification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_check_employers', to='auth_account.employerlettermethod', verbose_name='Work Experience Verification'),
        ),
    ]
