# Generated by Django 5.1.4 on 2023-04-18 15:07

from django.db import migrations


def copy_to_contactables(apps, schema_editor):
    Contact = apps.get_model("auth_account", "Contact")
    Contactable = apps.get_model("auth_account", "Contactable")
    Profile = apps.get_model("auth_account", "Profile")

    Contact.objects.all().update(contactable=None)

    for profile in Profile.objects.all():
        user = profile.user
        contactable = Contactable.objects.create()
        Profile.objects.filter(pk=profile.pk).update(contactable=contactable)
        user.contacts.update(contactable_id=contactable.pk)

    Contactable.objects.filter(profile__isnull=True, contacts__isnull=True).delete()


def reverse_copy_to_contactables(apps, schema_editor):
    return


class Migration(migrations.Migration):
    dependencies = [
        ("auth_account", "0024_merge_20241219_1955"),
    ]

    operations = [
        migrations.RunPython(copy_to_contactables, reverse_copy_to_contactables),
    ]
