# Generated by Django 5.1.4 on 2023-05-15 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0025_fix_profile_contactables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='about_me',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='headline',
        ),
    ]
