# Generated by Django 5.1.2 on 2024-10-24 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0025_alter_referencecheckemployer_work_experience_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencecheckemployer',
            name='work_experience_verification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employers', to='auth_account.employerlettermethod', verbose_name='Work Experience Verification'),
        ),
    ]
