# Generated by Django 5.1.4 on 2023-05-16 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0026_remove_resume_about_me_remove_resume_headline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='available_jobs',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='raw_skills',
        ),
        migrations.RemoveField(
            model_name='user',
            name='skills',
        ),
    ]
