# Generated by Django 5.1.1 on 2024-10-25 12:34

import account.models
import common.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0026_alter_referencecheckemployer_work_experience_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateAndLicenseOfflineVerificationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verified At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('certificate_file', models.FileField(upload_to=account.models.certificate_and_license_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png']), common.validators.ValidateFileSize(max=5)], verbose_name='Certificate And License')),
                ('certificate_and_license', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth_account.certificateandlicense', verbose_name='Certificate And License')),
            ],
            options={
                'verbose_name': 'Certificate And License Offline Verification Method',
                'verbose_name_plural': 'Certificate And License Offline Verification Methods',
            },
        ),
        migrations.CreateModel(
            name='CertificateAndLicenseOnlineVerificationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verified At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('certificate_link', models.URLField(verbose_name='Link')),
                ('certificate_and_license', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth_account.certificateandlicense', verbose_name='Certificate And License')),
            ],
            options={
                'verbose_name': 'Certificate And License Online Verification Method',
                'verbose_name_plural': 'Certificate And License Online Verification Methods',
            },
        ),
        migrations.DeleteModel(
            name='CertificateAndLicenseVerificationMethod',
        ),
    ]
