# Generated by Django 5.1.1 on 2024-10-28 10:14

import account.models
import common.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0027_certificateandlicenseofflineverificationmethod_and_more'),
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanadaVisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('study_permit', 'Study Permit'), ('work_permit', 'Work Permit'), ('permanent_residency', 'Permanent Residency'), ('visitor_visa', 'Visitor Visa'), ('refugee_status', 'Refugee Status'), ('citizenship', 'Citizenship'), ('temporary_residency', 'Temporary Residency'), ('pending', 'Pending'), ('other', 'Other')], default='pending', max_length=50, verbose_name='Status')),
                ('citizenship_document', models.FileField(upload_to=account.models.citizenship_document_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png']), common.validators.ValidateFileSize(max=5)], verbose_name='Citizenship Document')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canada_visas', to='cities_light.country', verbose_name='Nationality')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='canada_visa', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
