# Generated by Django 5.1.1 on 2023-05-30 08:40

import account.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0027_remove_user_available_jobs_remove_user_birth_date_and_more'),
        ('flex_blob', '0002_filemodel_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='created_by',
        ),
        migrations.AddField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('drafted', 'Drafted'), ('submitted', 'Submitted'), ('rejected', 'Rejected'), ('verified', 'Verified')], default='drafted', max_length=50, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='organization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='organization',
            name='user',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Verified At'),
        ),
        migrations.CreateModel(
            name='CommunicateOrganizationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verified At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('email_code', models.CharField(default=account.models.generate_unique_verification_code, max_length=6, verbose_name='Email Verification Code')),
                ('phone_code', models.CharField(default=account.models.generate_unique_verification_code, max_length=6, verbose_name='Phone Verification Code')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth_account.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Communicate Organization Method',
                'verbose_name_plural': 'Communicate Organization Methods',
            },
        ),
        migrations.CreateModel(
            name='DNSTXTRecordMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verified At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('code', models.CharField(default=account.models.generate_dnc_txt_record_code, max_length=20, unique=True, verbose_name='Record')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth_account.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'DNSTXT Record Method',
                'verbose_name_plural': 'DNSTXT Record Methods',
            },
        ),
        migrations.CreateModel(
            name='OrganizationCertificateFile',
            fields=[
                ('filemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flex_blob.filemodel')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization Certificate File',
                'verbose_name_plural': 'Organization Certificate Files',
            },
            bases=('flex_blob.filemodel',),
        ),
        migrations.CreateModel(
            name='UploadCompanyCertificateMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verified At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth_account.organization', verbose_name='Organization')),
                ('organization_certificate_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='upload_company_certificate_method', to='auth_account.organizationcertificatefile', verbose_name='Organization Certificate')),
            ],
            options={
                'verbose_name': 'Upload Company Certificate Method',
                'verbose_name_plural': 'Upload Company Certificate Methods',
            },
        ),
        migrations.CreateModel(
            name='UploadFileToWebsiteMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verified At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('file_name', models.CharField(default=account.models.generate_unique_file_name, max_length=30, unique=True, verbose_name='File Name')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth_account.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Upload File To Website Method',
                'verbose_name_plural': 'Upload File To Website Methods',
            },
        ),
    ]
