# Generated by Django 5.1.1 on 2024-10-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0028_canadavisa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canadavisa',
            name='status',
            field=models.CharField(choices=[('study_permit', 'Study Permit'), ('work_permit', 'Work Permit'), ('permanent_residency', 'Permanent Residency'), ('visitor_visa', 'Visitor Visa'), ('refugee_status', 'Refugee Status'), ('citizenship', 'Citizenship'), ('temporary_residency', 'Temporary Residency'), ('pending', 'Pending'), ('other', 'Other')], max_length=50, verbose_name='Status'),
        ),
    ]
