# Generated by Django 5.1.1 on 2024-12-23 11:52

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0028_remove_organization_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dnstxtrecordmethod',
            options={'verbose_name': 'DNS TXT Record Method', 'verbose_name_plural': 'DNS TXT Record Methods'},
        ),
        migrations.AlterField(
            model_name='dnstxtrecordmethod',
            name='code',
            field=models.CharField(default=account.models.generate_dnc_txt_record_code, max_length=20, unique=True, verbose_name='code'),
        ),
    ]
