# Generated by Django 5.1.1 on 2023-07-04 09:39

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0029_alter_dnstxtrecordmethod_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communicateorganizationmethod',
            name='email_code',
        ),
        migrations.RemoveField(
            model_name='communicateorganizationmethod',
            name='phone_code',
        ),
        migrations.AddField(
            model_name='communicateorganizationmethod',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='communicateorganizationmethod',
            name='is_phonenumber_verified',
            field=models.BooleanField(default=False, verbose_name='Is Phone Number Verified'),
        ),
        migrations.AddField(
            model_name='communicateorganizationmethod',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+989123700000', max_length=128, region=None, verbose_name='Phone Number'),
            preserve_default=False,
        ),
    ]
