# Generated by Django 5.1.1 on 2024-11-01 09:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0029_alter_canadavisa_status'),
        ('common', '0007_languageproficiencytest_overall_max_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='available_jobs',
            field=models.ManyToManyField(blank=True, to='common.job', verbose_name='Available Jobs'),
        ),
        migrations.AddField(
            model_name='user',
            name='raw_skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, null=True, size=None, verbose_name='Raw Skills'),
        ),
    ]
