# Generated by Django 5.1.1 on 2024-11-05 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0030_user_available_jobs_user_raw_skills'),
        ('common', '0009_jobassessment_jobassessmentjob_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('started', 'Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('timeout', 'Timeout')], default='not_started', max_length=64, verbose_name='Status')),
                ('score', models.JSONField(blank=True, null=True, verbose_name='Score')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('job_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='common.jobassessment', verbose_name='Job Assessment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_assessment_results', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Job Assessment Result',
                'verbose_name_plural': 'Job Assessment Results',
            },
        ),
    ]
