# Generated by Django 5.1.1 on 2024-11-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0031_jobassessmentresult'),
        ('common', '0010_alter_jobassessmentjob_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job_assessment_bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_by', to='common.jobassessment', verbose_name='Job Assessment Bookmarks'),
        ),
    ]
