# Generated by Django 5.1.1 on 2024-12-28 18:22

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0031_alter_organizationmembership_user'),
        ('common', '0003_alter_skill_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationJobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('vaccancy', models.PositiveIntegerField(blank=True, null=True, verbose_name='Vacancy')),
                ('start_at', models.DateField(blank=True, null=True, verbose_name='Start At')),
                ('validity_date', models.DateField(blank=True, null=True, verbose_name='Validity Date')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('work_experience_years', models.PositiveIntegerField(blank=True, null=True, verbose_name='Work Experience Years')),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('af', 'Afrikaans'), ('ar', 'Arabic'), ('ar-dz', 'Algerian Arabic'), ('ast', 'Asturian'), ('az', 'Azerbaijani'), ('bg', 'Bulgarian'), ('be', 'Belarusian'), ('bn', 'Bengali'), ('br', 'Breton'), ('bs', 'Bosnian'), ('ca', 'Catalan'), ('ckb', 'Central Kurdish (Sorani)'), ('cs', 'Czech'), ('cy', 'Welsh'), ('da', 'Danish'), ('de', 'German'), ('dsb', 'Lower Sorbian'), ('el', 'Greek'), ('en', 'English'), ('en-au', 'Australian English'), ('en-gb', 'British English'), ('eo', 'Esperanto'), ('es', 'Spanish'), ('es-ar', 'Argentinian Spanish'), ('es-co', 'Colombian Spanish'), ('es-mx', 'Mexican Spanish'), ('es-ni', 'Nicaraguan Spanish'), ('es-ve', 'Venezuelan Spanish'), ('et', 'Estonian'), ('eu', 'Basque'), ('fa', 'Persian'), ('fi', 'Finnish'), ('fr', 'French'), ('fy', 'Frisian'), ('ga', 'Irish'), ('gd', 'Scottish Gaelic'), ('gl', 'Galician'), ('he', 'Hebrew'), ('hi', 'Hindi'), ('hr', 'Croatian'), ('hsb', 'Upper Sorbian'), ('hu', 'Hungarian'), ('hy', 'Armenian'), ('ia', 'Interlingua'), ('id', 'Indonesian'), ('ig', 'Igbo'), ('io', 'Ido'), ('is', 'Icelandic'), ('it', 'Italian'), ('ja', 'Japanese'), ('ka', 'Georgian'), ('kab', 'Kabyle'), ('kk', 'Kazakh'), ('km', 'Khmer'), ('kn', 'Kannada'), ('ko', 'Korean'), ('ky', 'Kyrgyz'), ('lb', 'Luxembourgish'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('mk', 'Macedonian'), ('ml', 'Malayalam'), ('mn', 'Mongolian'), ('mr', 'Marathi'), ('ms', 'Malay'), ('my', 'Burmese'), ('nb', 'Norwegian Bokmål'), ('ne', 'Nepali'), ('nl', 'Dutch'), ('nn', 'Norwegian Nynorsk'), ('os', 'Ossetic'), ('pa', 'Punjabi'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('pt-br', 'Brazilian Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sq', 'Albanian'), ('sr', 'Serbian'), ('sr-latn', 'Serbian Latin'), ('sv', 'Swedish'), ('sw', 'Swahili'), ('ta', 'Tamil'), ('te', 'Telugu'), ('tg', 'Tajik'), ('th', 'Thai'), ('tk', 'Turkmen'), ('tr', 'Turkish'), ('tt', 'Tatar'), ('udm', 'Udmurt'), ('ug', 'Uyghur'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('uz', 'Uzbek'), ('vi', 'Vietnamese'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese')], max_length=32), blank=True, null=True, size=None, verbose_name='Languages')),
                ('age_range', models.CharField(blank=True, choices=[('_18_25', '18-25'), ('_26_35', '26-35'), ('_36_45', '36-45'), ('_46_55', '46-55'), ('_56_65', '56-65'), ('over_65', 'Over 65')], max_length=50, null=True, verbose_name='Age Range')),
                ('required_document', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None, verbose_name='Required Document')),
                ('performance_expectation', models.TextField(blank=True, null=True, verbose_name='Performance Expectation')),
                ('contract_type', models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('remote', 'Remote'), ('temporary', 'Temporary'), ('internship', 'Internship'), ('contract', 'Contract'), ('freelance', 'Freelance')], max_length=50, null=True, verbose_name='Contract Type')),
                ('salary_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='Salary Min')),
                ('salary_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='Salary Max')),
                ('payment_term', models.CharField(blank=True, choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=50, null=True, verbose_name='Payment Term')),
                ('working_start_at', models.TimeField(blank=True, null=True, verbose_name='Working Start At')),
                ('working_end_at', models.TimeField(blank=True, null=True, verbose_name='Working End At')),
                ('benefits', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None, verbose_name='Benefits')),
                ('days_off', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=50), blank=True, null=True, size=None, verbose_name='Days Off')),
                ('job_restrictions', models.TextField(blank=True, null=True, verbose_name='Job Restrictions')),
                ('employer_questions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None, verbose_name='Employer Questions')),
                ('status', models.CharField(choices=[('drafted', 'Drafted'), ('published', 'Published'), ('completed', 'Completed'), ('suspended', 'Suspended'), ('expired', 'Expired'), ('closed', 'Closed')], default='drafted', max_length=50, verbose_name='Status')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Closed At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('educations', models.ManyToManyField(related_name='job_positions', to='common.field', verbose_name='Educations')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_positions', to='auth_account.organization')),
                ('skills', models.ManyToManyField(related_name='job_positions', to='common.skill', verbose_name='Skills')),
            ],
            options={
                'verbose_name': 'Organization Job Position',
                'verbose_name_plural': 'Organization Job Positions',
            },
        ),
    ]
