# Generated by Django 5.1.1 on 2024-11-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0032_profile_job_assessment_bookmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobassessmentresult',
            name='user_score',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True),
        ),
    ]
