# Generated by Django 5.1.1 on 2024-12-31 15:29

import django.contrib.postgres.fields
import django.db.models.deletion
import markdownfield.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0033_organizationjobposition_native_languages'),
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('common', '0004_jobbenefit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationjobposition',
            old_name='required_document',
            new_name='required_documents',
        ),
        migrations.RemoveField(
            model_name='organizationjobposition',
            name='age_range',
        ),
        migrations.RemoveField(
            model_name='organizationjobposition',
            name='closed_at',
        ),
        migrations.RemoveField(
            model_name='organizationjobposition',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='organizationjobposition',
            name='educations',
        ),
        migrations.RemoveField(
            model_name='organizationjobposition',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='organizationjobposition',
            name='status',
        ),
        migrations.RemoveField(
            model_name='organizationjobposition',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='organizationjobposition',
            name='_status',
            field=models.CharField(choices=[('drafted', 'Drafted'), ('published', 'Published'), ('completed', 'Completed'), ('suspended', 'Suspended'), ('expired', 'Expired')], default='drafted', max_length=50, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='organizationjobposition',
            name='age_max',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Age Max'),
        ),
        migrations.AddField(
            model_name='organizationjobposition',
            name='age_min',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Age Min'),
        ),
        migrations.AddField(
            model_name='organizationjobposition',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_positions', to='cities_light.city', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='organizationjobposition',
            name='degrees',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('bachelors', 'Bachelors'), ('masters', 'Masters'), ('phd', 'PhD'), ('associate', 'Associate'), ('diploma', 'Diploma'), ('certificate', 'Certificate')], max_length=50), blank=True, null=True, size=None, verbose_name='Degree'),
        ),
        migrations.AddField(
            model_name='organizationjobposition',
            name='fields',
            field=models.ManyToManyField(related_name='job_positions', to='common.field', verbose_name='Fields'),
        ),
        migrations.AddField(
            model_name='organizationjobposition',
            name='location_type',
            field=models.CharField(blank=True, choices=[('onsite', 'Onsite'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], max_length=50, null=True, verbose_name='Location Type'),
        ),
        migrations.RemoveField(
            model_name='organizationjobposition',
            name='benefits',
        ),
        migrations.AlterField(
            model_name='organizationjobposition',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('temporary', 'Temporary'), ('internship', 'Internship'), ('contract', 'Contract'), ('freelance', 'Freelance')], max_length=50, null=True, verbose_name='Contract Type'),
        ),
        migrations.AlterField(
            model_name='organizationjobposition',
            name='description',
            field=markdownfield.models.MarkdownField(blank=True, null=True, rendered_field='description_rendered'),
        ),
        migrations.AlterField(
            model_name='organizationjobposition',
            name='performance_expectation',
            field=markdownfield.models.MarkdownField(blank=True, null=True, rendered_field='performance_expectation_rendered'),
        ),
        migrations.CreateModel(
            name='OrganizationJobPositionStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('drafted', 'Drafted'), ('published', 'Published'), ('completed', 'Completed'), ('suspended', 'Suspended'), ('expired', 'Expired')], max_length=50, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('job_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_histories', to='auth_account.organizationjobposition')),
            ],
            options={
                'verbose_name': 'Status History',
                'verbose_name_plural': 'Status Histories',
            },
        ),
        migrations.AddField(
            model_name='organizationjobposition',
            name='benefits',
            field=models.ManyToManyField(related_name='job_positions', to='common.jobbenefit', verbose_name='Benefits'),
        ),
    ]
