# Generated by Django 5.1.1 on 2024-11-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0033_jobassessmentresult_user_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobassessmentresult',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('timeout', 'Timeout')], default='not_started', max_length=64, verbose_name='Status'),
        ),
    ]
