# Generated by Django 5.1.1 on 2024-11-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0034_alter_jobassessmentresult_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobassessmentresult',
            name='user_score',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='skills',
        ),
        migrations.AddField(
            model_name='jobassessmentresult',
            name='raw_score',
            field=models.JSONField(blank=True, null=True, verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='jobassessmentresult',
            name='score',
            field=models.CharField(blank=True, choices=[('average', 'Average'), ('good', 'Good'), ('greate', 'Great'), ('exceptional', 'Exceptional')], editable=False, max_length=32, null=True),
        ),
    ]
