# Generated by Django 5.1.1 on 2024-11-08 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0035_remove_jobassessmentresult_user_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='job_assessment_bookmarks',
        ),
        migrations.DeleteModel(
            name='JobAssessmentResult',
        ),
    ]
