# Generated by Django 5.1.1 on 2024-12-31 17:54

import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0035_access_alter_organizationjobposition_benefits_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationjobposition',
            name='age_max',
        ),
        migrations.RemoveField(
            model_name='organizationjobposition',
            name='age_min',
        ),
        migrations.RemoveField(
            model_name='organizationjobposition',
            name='salary_max',
        ),
        migrations.RemoveField(
            model_name='organizationjobposition',
            name='salary_min',
        ),
        migrations.AddField(
            model_name='organizationjobposition',
            name='age_range',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, null=True, verbose_name='Age Range'),
        ),
        migrations.AddField(
            model_name='organizationjobposition',
            name='other_benefits',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None, verbose_name='Other Benefits'),
        ),
        migrations.AddField(
            model_name='organizationjobposition',
            name='salary_range',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, null=True, verbose_name='Salary Range'),
        ),
    ]
