# Generated by Django 5.1.4 on 2023-08-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0036_remove_organizationjobposition_age_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='slug',
            field=models.SlugField(default='admin', max_length=255, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
