# Generated by Django 5.1.4 on 2023-08-19 15:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth_account", "0037_role_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="role",
            name="accesses",
        ),
    ]
