# Generated by Django 5.1.3 on 2024-11-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0038_alter_resume_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='resume_text',
            field=models.TextField(blank=True, null=True, verbose_name='Resume Text'),
        ),
    ]
