# Generated by Django 5.1.4 on 2023-08-27 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0039_roleaccess_role_accesses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationinvitation',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='organization_invitations', to='auth_account.role', verbose_name='Role'),
        ),
    ]
