# Generated by Django 5.1.3 on 2024-11-11 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0039_resume_resume_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='resume_text',
            new_name='text',
        ),
    ]
