# Generated by Django 5.1.4 on 2023-08-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_account", "0040_alter_organizationinvitation_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organizationmembership",
            name="access_role",
        ),
        migrations.RemoveField(
            model_name="organizationmembership",
            name="role",
        ),
        migrations.AlterField(
            model_name="access",
            name="slug",
            field=models.SlugField(max_length=255, unique=True, verbose_name="Slug"),
        ),
    ]
