# Generated by Django 5.1.3 on 2024-11-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0040_rename_resume_text_resume_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='text',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='Resume Text'),
        ),
    ]
