# Generated by Django 5.1.3 on 2024-11-11 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0041_alter_resume_text'),
        ('common', '0013_skill_insert_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(editable=False, related_name='users', to='common.skill', verbose_name='Skills'),
        ),
    ]
