# Generated by Django 5.1.4 on 2025-01-02 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0041_remove_organizationmembership_access_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmembership',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='organization_memberships', to='auth_account.role', verbose_name='Access Role'),
            preserve_default=False,
        ),
    ]
