# Generated by Django 5.1.4 on 2025-01-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0042_organizationmembership_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allow_notifications',
            field=models.BooleanField(default=True, verbose_name='Allow Notifications'),
        ),
    ]
