# Generated by Django 5.1.1 on 2024-11-14 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0043_profile_native_language_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='native_language',
            new_name='native_languages',
        ),
    ]
