# Generated by Django 5.1.4 on 2025-01-03 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0043_profile_allow_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateandlicense',
            name='certificate_text',
            field=models.TextField(blank=True, null=True, verbose_name='Certificate Text'),
        ),
    ]
