# Generated by Django 5.1.1 on 2025-01-03 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0044_certificateandlicense_certificate_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPositionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_status', models.CharField(choices=[('not_reviewed', 'Not Reviewed'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='not_reviewed', max_length=50, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('job_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='auth_account.organizationjobposition', verbose_name='Job Position')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_position_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Job Seeker')),
            ],
            options={
                'verbose_name': 'Job Position Assignment',
                'verbose_name_plural': 'Job Position Assignments',
            },
        ),
        migrations.AddField(
            model_name='organizationjobposition',
            name='job_seeker_assignment',
            field=models.ManyToManyField(through='auth_account.JobPositionAssignment', to=settings.AUTH_USER_MODEL, verbose_name='Job Seeker Assignment'),
        ),
        migrations.CreateModel(
            name='JobPositionAssignmentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_reviewed', 'Not Reviewed'), ('rejected', 'Rejected'), ('hired', 'Hired'), ('awaiting_interview_date', 'Awaiting Interview Date'), ('interview_scheduled', 'Interview Scheduled'), ('interviewing', 'Interviewing'), ('awaiting_interview_results', 'Awaiting Interview Results'), ('interview_canceled_by_jobseeker', 'Interview Canceled By Jobseeker'), ('interview_canceled_by_employer', 'Interview Canceled By Employer'), ('rejected_at_interview', 'Rejected At Interview')], max_length=50, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('job_position_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_histories', to='auth_account.jobpositionassignment')),
            ],
            options={
                'verbose_name': 'Job Position Assignment Status History',
                'verbose_name_plural': 'Job Position Assignment Status Histories',
            },
        ),
        migrations.CreateModel(
            name='JobPositionInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('awaiting_interview_date', 'Awaiting Interview Date'), ('interview_scheduled', 'Interview Scheduled'), ('interviewing', 'Interviewing'), ('awaiting_interview_results', 'Awaiting Interview Results'), ('interview_canceled_by_jobseeker', 'Interview Canceled By Jobseeker'), ('interview_canceled_by_employer', 'Interview Canceled By Employer'), ('rejected_at_interview', 'Rejected At Interview')], default='awaiting_interview_date', max_length=50, verbose_name='Status')),
                ('interview_date', models.DateTimeField(verbose_name='Interview Date')),
                ('result_date', models.DateTimeField(verbose_name='Result Date')),
                ('job_position_assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview', to='auth_account.jobpositionassignment')),
            ],
        ),
    ]
