# Generated by Django 5.1.1 on 2025-01-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0045_jobpositionassignment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobpositioninterview',
            options={'verbose_name': 'Job Position Interview', 'verbose_name_plural': 'Job Position Interviews'},
        ),
        migrations.AlterField(
            model_name='jobpositioninterview',
            name='interview_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Interview Date'),
        ),
        migrations.AlterField(
            model_name='jobpositioninterview',
            name='result_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Result Date'),
        ),
    ]
