# Generated by Django 5.1.1 on 2024-11-18 08:41

import account.models
import common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0045_alter_canadavisa_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ieemethod',
            name='citizen_document',
        ),
        migrations.RemoveField(
            model_name='ieemethod',
            name='ices_document',
        ),
        migrations.AddField(
            model_name='communicationmethod',
            name='website',
            field=models.URLField(default='https://university.com', verbose_name='Website'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ieemethod',
            name='education_evaluation_document',
            field=models.FileField(default=None, upload_to=account.models.education_evaluation_document_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png']), common.validators.ValidateFileSize(max=5)], verbose_name='Education Evaluation Document'),
        ),
    ]
