# Generated by Django 5.1.4 on 2025-01-04 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0047_remove_jobpositionassignment__status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationinvitation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='auth_account.organization', verbose_name='Organization'),
        ),
    ]
