# Generated by Django 5.1.4 on 2023-10-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0048_alter_organizationinvitation_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accept_terms_and_conditions',
            field=models.BooleanField(default=False, verbose_name='Accept Terms'),
        ),
    ]
