# Generated by Django 5.1.4 on 2023-09-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_account", "0048_alter_organizationinvitation_organization"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportTicketCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(max_length=255, unique=True, verbose_name="Slug")),
                ("title", models.CharField(blank=True, max_length=255, null=True, verbose_name="Title")),
            ],
            options={
                "verbose_name": "Support Ticket Category",
                "verbose_name_plural": "Support Ticket Categories",
            },
        ),
        migrations.RenameField(
            model_name="access",
            old_name="description",
            new_name="title",
        ),
        migrations.AlterField(
            model_name="access",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="role",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Title"),
        ),
    ]
