# Generated by Django 5.1.4 on 2023-10-01 13:01

import model_utils.fields

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0049_supportticketcategory_remove_access_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportticket',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='supportticket',
            old_name='updated_at',
            new_name='modified',
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.RenameField(
            model_name='supportticket',
            old_name='category',
            new_name='old_category',
        ),
        migrations.AddField(
            model_name='supportticketcategory',
            name='is_job_seeker',
            field=models.BooleanField(default=False, verbose_name='Is Job Seeker'),
        ),
        migrations.AddField(
            model_name='supportticketcategory',
            name='is_organization',
            field=models.BooleanField(default=False, verbose_name='Is Organization'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='auth_account.supportticketcategory', verbose_name='Category', null=True, blank=True),
        ),
    ]
