# Generated by Django 5.1.4 on 2025-01-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_account", "0050_remove_supportticket_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supportticket",
            name="category",
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                null=True,
                related_name="support_tickets",
                to="auth_account.supportticketcategory",
                verbose_name="Category",
            ),
        ),
        migrations.RemoveField(
            model_name="supportticket",
            name="old_category",
        ),
    ]
