# Generated by Django 5.1.4 on 2025-01-06 13:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth_account", "0050_remove_supportticket_created_at_and_more"),
    ]

    operations = []
