# Generated by Django 5.1.4 on 2025-01-06 13:04

from django.db import migrations, models

from ..populators import SupportTicketCategoryPopulator


def populate_categories(apps, schema_editor):
    SupportTicketCategoryPopulator().populate()


CONVERT_SUPPORT_TICKET_CATEGORIES_TO_TABLE = """
UPDATE auth_account_supportticket AS st
SET category_id = (
    SELECT id FROM auth_account_supportticketcategory AS cat
    WHERE cat.slug = st.old_category
)
WHERE st.old_category IS NOT NULL;
"""


CONVERT_SUPPORT_TICKET_CATEGORIES_TO_TABLE_REVERSE = """
UPDATE auth_account_supportticket AS st
SET old_category = (
    SELECT slug FROM auth_account_supportticketcategory AS cat
    WHERE cat.id = st.category_id
)
WHERE st.category_id IS NOT NULL;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("auth_account", "0050_remove_supportticket_created_at_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_categories, reverse_code=populate_categories),
        migrations.RunSQL(
            CONVERT_SUPPORT_TICKET_CATEGORIES_TO_TABLE,
            reverse_sql=CONVERT_SUPPORT_TICKET_CATEGORIES_TO_TABLE_REVERSE,
        ),
        migrations.AlterField(
            model_name="supportticket",
            name="category",
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                related_name="support_tickets",
                to="auth_account.supportticketcategory",
                verbose_name="Category",
            ),
        ),
        migrations.RemoveField(
            model_name="supportticket",
            name="old_category",
        ),
    ]
