# Generated by Django 5.1.1 on 2024-11-20 10:05

import account.models
import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0050_alter_profile_native_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.avatar_path, validators=[common.validators.ValidateFileSize(max=3)], verbose_name='Avatar'),
        ),
    ]
