# Generated by Django 5.1.4 on 2025-01-06 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0051_fix_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='text',
        ),
    ]
