# Generated by Django 5.1.3 on 2024-11-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0052_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canadavisa',
            name='status',
            field=models.CharField(choices=[('citizenship', 'Citizenship'), ('permanent_resident', 'Permanent Resident (PR)'), ('temporary_resident_open_work_permit', 'Temporary Resident (Open Work Permit)'), ('temporary_resident_close_work_permit', 'Temporary Resident (Close Work Permit)'), ('temporary_resident_study_permit', 'Temporary Resident (Study Permit)'), ('refugee_work_permit', 'Refugee (Work Permit)'), ('seasonal_agricultural_worker_program', 'Seasonal Agricultural Worker Program (SAWP)'), ('international_experience_canada', 'International Experience Canada (IEC)'), ('electronic_travel_authorization', 'Electronic Travel Authorization (eTA)'), ('visitor_visa', 'Visitor Visa')], max_length=50, verbose_name='Status'),
        ),
    ]
