# Generated by Django 5.1.4 on 2023-10-01 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0049_profile_accept_terms_and_conditions'),
        ('auth_account', '0052_remove_resume_text'),
    ]

    operations = [
    ]
