# Generated by Django 5.1.3 on 2024-11-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0053_alter_canadavisa_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='credits',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
