# Generated by Django 5.1.1 on 2025-01-07 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0053_merge_20250106_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
    ]
