# Generated by Django 5.1.4 on 2025-01-07 10:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0054_remove_contact_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticketcategory',
            name='is_job_seeker',
        ),
        migrations.RemoveField(
            model_name='supportticketcategory',
            name='is_organization',
        ),
        migrations.RemoveField(
            model_name='supportticketcategory',
            name='slug',
        ),
        migrations.AddField(
            model_name='supportticketcategory',
            name='types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('organization', 'Organization'), ('job_seeker', 'Job Seeker')], max_length=50), default=['organization'], size=None, verbose_name='Types'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supportticketcategory',
            name='title',
            field=models.CharField(default='Support', max_length=255, unique=True, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
