# Generated by Django 5.1.3 on 2024-11-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0054_profile_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='credits',
            field=models.IntegerField(editable=False, verbose_name='Credits'),
        ),
    ]
