# Generated by Django 5.1.3 on 2024-11-22 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0055_alter_profile_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referraluser',
            name='referral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_users', to='auth_account.referral'),
        ),
        migrations.AlterField(
            model_name='referraluser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
    ]
