# Generated by Django 5.1.4 on 2023-10-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0055_remove_supportticketcategory_is_job_seeker_and_more'),
        ('common', '0004_jobbenefit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='common.skill', verbose_name='Skills'),
        ),
    ]
