# Generated by Django 5.1.3 on 2024-11-22 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0056_alter_referraluser_referral_alter_referraluser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='referred_users',
        ),
        migrations.AlterField(
            model_name='referraluser',
            name='referral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_users', to='auth_account.referral'),
        ),
        migrations.AlterField(
            model_name='referraluser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_source', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['code'], name='auth_accoun_code_3f95ce_idx'),
        ),
    ]
