# Generated by Django 5.1.1 on 2023-10-10 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0056_alter_profile_skills'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportticketcategory',
            options={'ordering': ['title'], 'verbose_name': 'Support Ticket Category', 'verbose_name_plural': 'Support Ticket Categories'},
        ),
    ]
