# Generated by Django 5.1.1 on 2025-01-07 15:06

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0057_alter_supportticketcategory_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationjobposition',
            name='work_experience_years',
        ),
        migrations.AddField(
            model_name='organizationjobposition',
            name='work_experience_years_range',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, null=True, verbose_name='Age Range'),
        ),
    ]
