# Generated by Django 5.1.3 on 2024-12-02 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_account", "0057_remove_referral_referred_users_and_more"),
        ("flex_blob", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Avatar",
            fields=[
                (
                    "basefilemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="flex_blob.basefilemodel",
                    ),
                ),
                (
                    "uploaded_by",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_avatar",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=("flex_blob.basefilemodel",),
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to="auth_account.avatar",
            ),
        ),
    ]
