# Generated by Django 5.1.4 on 2023-10-18 12:51

from django.db import migrations, models

from ..populators import SupportTicketCategoryPopulator


def populate_categories(apps, schema_editor):
    SupportTicketCategoryPopulator().populate()


def add_default_categories(apps, schema_editor):
    SupportTicket = apps.get_model("auth_account", "SupportTicket")
    SupportTicketCategory = apps.get_model("auth_account", "SupportTicketCategory")
    for st in SupportTicket.objects.all():
        if not st.category:
            st.category = SupportTicketCategory.objects.filter(title="Profile").first()
            st.save()


class Migration(migrations.Migration):
    dependencies = [
        ("auth_account", "0058_remove_organizationjobposition_work_experience_years_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_categories, reverse_code=populate_categories),
        migrations.RunPython(add_default_categories, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="supportticket",
            name="category",
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                related_name="support_tickets",
                to="auth_account.supportticketcategory",
                verbose_name="Category",
            ),
        ),
    ]
