# Generated by Django 5.1.4 on 2025-01-07 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0058_remove_organizationjobposition_work_experience_years_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticket',
            name='old_category',
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='auth_account.supportticketcategory', verbose_name='Category'),
        ),
    ]
