# Generated by Django 5.1.3 on 2024-12-03 08:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth_account", "0058_avatar_profile_avatar2"),
        ("flex_blob", "0002_alter_basefilemodel_file"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Avatar",
            new_name="AvatarFile",
        ),
    ]
