# Generated by Django 5.1.1 on 2023-11-03 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0059_auto_20250108_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpositionassignment',
            name='interview_date',
        ),
        migrations.RemoveField(
            model_name='jobpositionassignment',
            name='result_date',
        ),
        migrations.CreateModel(
            name='JobPositionInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateTimeField(verbose_name='Interview Date')),
                ('result_date', models.DateTimeField(blank=True, null=True, verbose_name='Result Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('job_position_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='auth_account.jobpositionassignment', verbose_name='Job Position Assignment')),
            ],
            options={
                'verbose_name': 'Job Position Interview',
                'verbose_name_plural': 'Job Position Interviews',
            },
        ),
    ]
