# Generated by Django 5.1.3 on 2024-12-03 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0059_rename_avatar_avatarfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatarfile',
            old_name='basefilemodel_ptr',
            new_name='filemodel_ptr',
        ),
    ]
