# Generated by Django 5.1.1 on 2023-11-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0060_remove_jobpositionassignment_interview_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationjobposition',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('permanent', 'Permanent'), ('fix_term_contract', 'Fix Term Contract'), ('seasonal', 'Seasonal'), ('freelance', 'Freelance'), ('apprenticeship', 'Apprenticeship'), ('prince_edward_island', 'Prince Edward Island'), ('internship_co_op', 'Internship/Co-op')], max_length=50, null=True, verbose_name='Contract Type'),
        ),
        migrations.AlterField(
            model_name='organizationjobposition',
            name='location_type',
            field=models.CharField(blank=True, choices=[('precise_location', 'On-site (Precise Location)'), ('limited_area', 'On-site (Within a Limited Area)'), ('remote', 'Remote'), ('hybrid', 'Hybrid'), ('on_the_road', 'On the road'), ('global', 'Global')], max_length=50, null=True, verbose_name='Location Type'),
        ),
    ]
