# Generated by Django 5.1.1 on 2025-01-13 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0061_alter_organizationjobposition_contract_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpositioninterview',
            name='assignment_status_history',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview', to='auth_account.jobpositionassignmentstatushistory'),
        ),
    ]
