# Generated by Django 5.1.4 on 2025-01-17 15:08

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0062_jobpositioninterview_assignment_status_history'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='profile',
            managers=[
                ('flex_report_custom_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
