# Generated by Django 5.1.1 on 2025-01-18 15:02

import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0063_alter_profile_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hiring_status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('terminated', 'Terminated'), ('dismissed', 'Dismissed')], default='active', max_length=50, verbose_name='Status')),
                ('cooperation_range', django.contrib.postgres.fields.ranges.DateRangeField(blank=True, null=True, verbose_name='Start End Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('job_position_assignment', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='organization_employee', to='auth_account.jobpositionassignment', verbose_name='Job Position Assignment ')),
            ],
            options={
                'verbose_name': 'Organization Employee',
                'verbose_name_plural': 'Organization Employees',
            },
        ),
    ]
