# Generated by Django 5.1.1 on 2025-01-21 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0065_alter_jobpositionassignment_status_and_more'),
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('common', '0005_alter_skill_insert_type_alter_skill_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canadavisa',
            name='nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='canada_visas', to='cities_light.country', verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='education',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cities_light.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='education',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='common.field', verbose_name='Field'),
        ),
        migrations.AlterField(
            model_name='education',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='common.university', verbose_name='University'),
        ),
        migrations.AlterField(
            model_name='jobpositioninterview',
            name='assignment_status_history',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='interview', to='auth_account.jobpositionassignmentstatushistory'),
        ),
        migrations.AlterField(
            model_name='languagecertificate',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='certificates', to='common.languageproficiencytest', verbose_name='Test'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='common.industry', verbose_name='Industry'),
        ),
        migrations.AlterField(
            model_name='organizationjobposition',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_positions', to='cities_light.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Invited By'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='work_experiences', to='cities_light.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='common.industry', verbose_name='Industry'),
        ),
    ]
