# Generated by Django 5.1.1 on 2024-02-07 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0066_alter_canadavisa_nationality_alter_education_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePlatformMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('ai', 'AI'), ('human', 'Human')], default='human', max_length=8, verbose_name='Source')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='auth_account.organizationemployee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Employee Platform Message',
                'verbose_name_plural': 'Employee Platform Messages',
            },
        ),
        migrations.CreateModel(
            name='OrganizationPlatformMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('ai', 'AI'), ('human', 'Human')], default='human', max_length=8, verbose_name='Source')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='auth_account.organizationemployee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Organization Platform Message',
                'verbose_name_plural': 'Organization Platform Messages',
            },
        ),
    ]
