# Generated by Django 5.1.1 on 2024-02-08 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0067_employeeplatformmessage_organizationplatformmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationemployee',
            name='cooperation_range',
        ),
        migrations.AddField(
            model_name='organizationemployee',
            name='cooperation_end_at',
            field=models.DateField(blank=True, null=True, verbose_name='Cooperation End At'),
        ),
        migrations.AddField(
            model_name='organizationemployee',
            name='cooperation_start_at',
            field=models.DateField(blank=True, null=True, verbose_name='Cooperation Start At'),
        ),
        migrations.AlterField(
            model_name='organizationemployee',
            name='hiring_status',
            field=models.CharField(choices=[('awaiting', 'Awaiting'), ('active', 'Active'), ('suspended', 'Suspended'), ('fired', 'Fired'), ('finished', 'Finished')], default='awaiting', max_length=50, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='OrganizationEmployeeHiringStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hiring_status', models.CharField(choices=[('awaiting', 'Awaiting'), ('active', 'Active'), ('suspended', 'Suspended'), ('fired', 'Fired'), ('finished', 'Finished')], max_length=50, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('organization_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_histories', to='auth_account.organizationemployee', verbose_name='Organization Employee')),
            ],
            options={
                'verbose_name': 'Organization Employee Hiring Status History',
                'verbose_name_plural': 'Organization Employee Hiring Status Histories',
            },
        ),
    ]
