# Generated by Django 5.1.1 on 2025-01-22 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0068_remove_organizationemployee_cooperation_range_and_more'),
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='cities_light.city', verbose_name='City'),
        ),
    ]
