# Generated by Django 5.1.1 on 2025-01-23 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0069_organization_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationjobposition',
            old_name='_status',
            new_name='status',
        ),
    ]
