# Generated by Django 5.1.1 on 2025-01-23 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0070_rename__status_organizationjobposition_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationemployee',
            name='cooperation_end_at',
        ),
        migrations.RemoveField(
            model_name='organizationemployee',
            name='cooperation_start_at',
        ),
        migrations.RemoveField(
            model_name='organizationemployeehiringstatushistory',
            name='organization_employee',
        ),
        migrations.AlterUniqueTogether(
            name='jobpositionassignment',
            unique_together={('job_seeker', 'job_position')},
        ),
        migrations.CreateModel(
            name='OrganizationEmployeeCooperationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateField(verbose_name='Start At')),
                ('end_at', models.DateField(blank=True, null=True, verbose_name='End At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooperation_histories', to='auth_account.organizationemployee', verbose_name='Organization Employee')),
            ],
            options={
                'verbose_name': 'Organization Employee Cooperation History',
                'verbose_name_plural': 'Organization Employee Cooperation Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='organizationemployeehiringstatushistory',
            name='cooperation_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiring_status_histories', to='auth_account.organizationemployeecooperationhistory', verbose_name='Cooperation History'),
        ),
    ]
