# Generated by Django 5.1.1 on 2025-01-23 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0071_remove_organizationemployee_cooperation_end_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationjobpositionstatushistory',
            options={'verbose_name': 'Organization Job Position Status History', 'verbose_name_plural': 'Organization Job Position Status Histories'},
        ),
    ]
