# Generated by Django 5.1.5 on 2025-01-27 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0072_alter_organizationjobpositionstatushistory_options'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='profile',
            managers=[
            ],
        ),
    ]
