# Generated by Django 5.1.4 on 2024-04-10 14:35

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0073_alter_profile_managers'),
        ('refresh_token', '0002_auto_20190130_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('device_id', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Device ID')),
                ('refresh_token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='refresh_token.refreshtoken', verbose_name='Refresh Token')),
            ],
            options={
                'verbose_name': 'User Device',
                'verbose_name_plural': 'User Devices',
                'unique_together': {('device_id', 'refresh_token')},
            },
        ),
    ]
