# Generated by Django 5.1.4 on 2024-04-11 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0074_userdevice'),
        ('auth_account', '0074_usertask_created_usertask_modified'),
    ]

    operations = [
    ]
