# Generated by Django 5.1.5 on 2024-04-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0075_merge_20250128_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='status',
            field=models.CharField(blank=True, choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('timedout', 'Timed-Out')], max_length=50, null=True, verbose_name='Status'),
        ),
    ]
