# Generated by Django 5.1.1 on 2025-01-29 15:35

import common.states
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_account", "0076_alter_usertask_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organizationemployeehiringstatushistory",
            name="cooperation_history",
        ),
        migrations.RemoveField(
            model_name="employeeplatformmessage",
            name="employee",
        ),
        migrations.RemoveField(
            model_name="organizationplatformmessage",
            name="employee",
        ),
        migrations.AddField(
            model_name="organization",
            name="employees",
            field=models.ManyToManyField(
                related_name="employee_organizations",
                through="auth_account.OrganizationEmployee",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="organizationemployee",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now, editable=False, verbose_name="created"
            ),
        ),
        migrations.AddField(
            model_name="organizationemployee",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now, editable=False, verbose_name="modified"
            ),
        ),
        migrations.AddField(
            model_name="organizationemployee",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organization_employees",
                to="auth_account.organization",
                verbose_name="Organization",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organizationemployee",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organization_employees",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="jobpositionassignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("awaiting_jobseeker_approval", "Awaiting Jobseeker Approval"),
                    ("rejected_by_jobseeker", "Rejected By Jobseeker"),
                    ("not_reviewed", "Not Reviewed"),
                    ("awaiting_interview_date", "Awaiting Interview Date"),
                    ("interview_scheduled", "Interview Scheduled"),
                    ("interviewing", "Interviewing"),
                    ("awaiting_interview_results", "Awaiting Interview Results"),
                    ("interview_canceled_by_jobseeker", "Interview Canceled By Jobseeker"),
                    ("interview_canceled_by_employer", "Interview Canceled By Employer"),
                    ("rejected_at_interview", "Rejected At Interview"),
                    ("rejected", "Rejected"),
                    ("accepted", "Accepted"),
                ],
                default="awaiting_jobseeker_approval",
                max_length=50,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="jobpositionassignmentstatushistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("awaiting_jobseeker_approval", "Awaiting Jobseeker Approval"),
                    ("rejected_by_jobseeker", "Rejected By Jobseeker"),
                    ("not_reviewed", "Not Reviewed"),
                    ("awaiting_interview_date", "Awaiting Interview Date"),
                    ("interview_scheduled", "Interview Scheduled"),
                    ("interviewing", "Interviewing"),
                    ("awaiting_interview_results", "Awaiting Interview Results"),
                    ("interview_canceled_by_jobseeker", "Interview Canceled By Jobseeker"),
                    ("interview_canceled_by_employer", "Interview Canceled By Employer"),
                    ("rejected_at_interview", "Rejected At Interview"),
                    ("rejected", "Rejected"),
                    ("accepted", "Accepted"),
                ],
                max_length=50,
                verbose_name="Status",
            ),
        ),
        migrations.CreateModel(
            name="OrganizationEmployeeCooperation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("awaiting", "Awaiting"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("fired", "Fired"),
                            ("finished", "Finished"),
                        ],
                        default="awaiting",
                        max_length=50,
                        verbose_name="Status",
                    ),
                ),
                ("start_at", models.DateTimeField(blank=True, null=True, verbose_name="Start At")),
                ("end_at", models.DateTimeField(blank=True, null=True, verbose_name="End At")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cooperations",
                        to="auth_account.organizationemployee",
                        verbose_name="Organization Employee",
                    ),
                ),
                (
                    "job_position_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cooperations",
                        to="auth_account.jobpositionassignment",
                        verbose_name="Job Position Assignment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Employee Cooperation",
                "verbose_name_plural": "Organization Employee Cooperation",
            },
            bases=(common.states.ChangeStateMixin, models.Model),
        ),
        migrations.AddField(
            model_name="employeeplatformmessage",
            name="organization_employee_cooperation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="auth_account.organizationemployeecooperation",
                verbose_name="Employee",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organizationplatformmessage",
            name="organization_employee_cooperation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="auth_account.organizationemployeecooperation",
                verbose_name="Employee",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="OrganizationEmployeeCooperationStatusHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("awaiting", "Awaiting"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("fired", "Fired"),
                            ("finished", "Finished"),
                        ],
                        max_length=50,
                        verbose_name="Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                (
                    "organization_employee_cooperation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_histories",
                        to="auth_account.organizationemployeecooperation",
                        verbose_name="Organization Employee Cooperation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Employee Cooperation Status History",
                "verbose_name_plural": "Organization Employee Cooperation Status Histories",
            },
        ),
        migrations.DeleteModel(
            name="OrganizationEmployeeCooperationHistory",
        ),
        migrations.DeleteModel(
            name="OrganizationEmployeeHiringStatusHistory",
        ),
        migrations.RemoveField(
            model_name="organizationemployee",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="organizationemployee",
            name="hiring_status",
        ),
        migrations.RemoveField(
            model_name="organizationemployee",
            name="job_position_assignment",
        ),
        migrations.AlterUniqueTogether(
            name="organizationemployee",
            unique_together={("user", "organization")},
        ),
    ]
