# Generated by Django 5.1.5 on 2025-02-01 13:43

import django.db.models.deletion
from django.db import migrations, models


def delete_null_contactables(apps, schema_editor):
    Contact = apps.get_model("auth_account", "Contact")
    Contact.objects.filter(contactable__isnull=True).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("auth_account", "0078_alter_organizationemployeecooperation_job_position_assignment"),
    ]

    operations = [
        migrations.RunPython(delete_null_contactables, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="contact",
            name="contactable",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="auth_account.contactable",
                verbose_name="Contactable",
            ),
        ),
    ]
