# Generated by Django 5.1.5 on 2024-05-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0079_alter_contact_contactable'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usertask',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='usertask',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['scheduled', 'in_progress'])), fields=('user', 'task_name'), name='unique_user_task_name_scheduled_or_in_progress'),
        ),
    ]
