# Generated by Django 5.1.5 on 2024-05-16 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0080_alter_usertask_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertask',
            options={'ordering': ['-created', 'task_name'], 'verbose_name': 'User Task', 'verbose_name_plural': 'User Tasks'},
        ),
    ]
