# Generated by Django 5.1.5 on 2024-05-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0081_alter_usertask_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('timedout', 'Timed-Out')], default='scheduled', max_length=50, verbose_name='Status'),
        ),
    ]
