# Generated by Django 5.1.5 on 2024-05-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0082_alter_usertask_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='status',
            field=models.CharField(blank=True, choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('timedout', 'Timed-Out')], max_length=50, null=True, verbose_name='Status'),
        ),
    ]
