# Generated by Django 5.1.4 on 2025-02-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0083_alter_usertask_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationemployeecooperation',
            name='status',
            field=models.CharField(choices=[('awaiting', 'Awaiting'), ('active', 'Active'), ('suspended', 'Suspended'), ('fired', 'Fired'), ('resigned', 'Resigned'), ('finished', 'Finished')], default='awaiting', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='organizationemployeecooperationstatushistory',
            name='status',
            field=models.CharField(choices=[('awaiting', 'Awaiting'), ('active', 'Active'), ('suspended', 'Suspended'), ('fired', 'Fired'), ('resigned', 'Resigned'), ('finished', 'Finished')], max_length=50, verbose_name='Status'),
        ),
    ]
