# Generated by Django 5.1.4 on 2024-06-03 16:19

from django.db import migrations


def delete_unregistered_user_tasks(apps, schema_editor):
    UserTask = apps.get_model("auth_account", "UserTask")
    UserTask.objects.filter(task_name="set_user_skills").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("auth_account", "0084_alter_organizationemployeecooperation_status_and_more"),
    ]

    operations = [
        migrations.RunPython(delete_unregistered_user_tasks, migrations.RunPython.noop),
    ]
