# Generated by Django 5.1.5 on 2025-02-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0085_auto_20250203_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ieemethod',
            name='evaluator',
            field=models.CharField(blank=True, choices=[('wes', 'World Education Services'), ('iqas', 'International Qualifications Assessment Service'), ('icas', 'International Credential Assessment Service of Canada'), ('ces', 'Comparative Education Service'), ('other', 'Other')], max_length=50, null=True, verbose_name='Academic Credential Evaluator'),
        ),
    ]
