# Generated by Django 5.1.5 on 2024-06-28 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0086_alter_ieemethod_evaluator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeplatformmessage',
            name='organization_employee_cooperation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='auth_account.organizationemployeecooperation', verbose_name='Employee Cooperation'),
        ),
        migrations.AlterField(
            model_name='organizationplatformmessage',
            name='organization_employee_cooperation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='auth_account.organizationemployeecooperation', verbose_name='Employee Cooperation'),
        ),
        migrations.CreateModel(
            name='OrganizationEmployeePerformanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Created'), ('completed', 'Completed')], default='created', max_length=50, verbose_name='Status')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('organization_employee_cooperation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='auth_account.organizationemployeecooperation', verbose_name='Employee Cooperation')),
            ],
            options={
                'verbose_name': 'Organization Employee Performance Report',
                'verbose_name_plural': 'Organization Employee Performance Reports',
            },
        ),
        migrations.CreateModel(
            name='OrganizationEmployeePerformanceReportStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Created'), ('completed', 'Completed')], max_length=50, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('organization_employee_performance_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_histories', to='auth_account.organizationemployeeperformancereport', verbose_name='Organization Employee Performance Report')),
            ],
            options={
                'verbose_name': 'Organization Employee Performance Report Status History',
                'verbose_name_plural': 'Organization Employee Performance Report Status Histories',
            },
        ),
    ]
