# Generated by Django 5.1.5 on 2025-02-07 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0088_alter_organization_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationPlatformMessageLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Text')),
                ('url', models.URLField(verbose_name='URL')),
                ('organization_platform_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='auth_account.organizationplatformmessage', verbose_name='Organization Platform Message')),
            ],
            options={
                'verbose_name': 'Organization Platform Message Link',
                'verbose_name_plural': 'Organization Platform Message Links',
            },
        ),
    ]
