# Generated by Django 5.1.4 on 2024-06-29 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0088_alter_organization_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='job_location_type',
            new_name='job_location_type_exclude',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='job_type',
            new_name='job_type_exclude',
        ),
    ]
