# Generated by Django 5.1.4 on 2024-06-30 20:00

from django.db import migrations


def invert_profile_job_type(apps, schema_editor):
    from account.models import Profile as ProfileModel

    Profile = apps.get_model("auth_account", "Profile")
    for profile in Profile.objects.all():
        profile.job_type_exclude = list(set(ProfileModel.JobType.values) - set(profile.job_type_exclude or []))
        profile.save(update_fields=["job_type_exclude"])


def invert_profile_job_location_type(apps, schema_editor):
    from account.models import Profile as ProfileModel

    Profile = apps.get_model("auth_account", "Profile")
    for profile in Profile.objects.all():
        profile.job_location_type_exclude = list(
            set(ProfileModel.JobLocationType.values) - set(profile.job_location_type_exclude or [])
        )
        profile.save(update_fields=["job_location_type_exclude"])


class Migration(migrations.Migration):
    dependencies = [
        ("auth_account", "0089_rename_job_location_type_profile_job_location_type_exclude_and_more"),
    ]

    operations = [
        migrations.RunPython(invert_profile_job_type, migrations.RunPython.noop),
        migrations.RunPython(invert_profile_job_location_type, migrations.RunPython.noop),
    ]
