# Generated by Django 5.1.5 on 2024-07-07 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0089_organizationplatformmessagelink'),
        ('auth_account', '0091_alter_profile_job_location_type_exclude_and_more'),
    ]

    operations = [
    ]
