# Generated by Django 5.1.5 on 2024-07-08 19:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0092_merge_20250207_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_type',
            field=models.CharField(choices=[('job_seeker', 'Job Seeker'), ('organization', 'Organization')], default='job_seeker', max_length=50, verbose_name='Registration Type'),
        ),
        migrations.AlterField(
            model_name='organizationjobposition',
            name='degrees',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('bachelors', 'Bachelors'), ('masters', 'Masters'), ('phd', 'PhD'), ('associate', 'Associate'), ('diploma', 'Diploma'), ('certificate', 'Certificate')], max_length=50), blank=True, null=True, size=None, verbose_name='Degrees'),
        ),
    ]
