# Generated by Django 5.1.6 on 2025-02-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0093_user_registration_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagecertificatevalue',
            name='value',
            field=models.TextField(verbose_name='Value'),
        ),
    ]
