# Generated by Django 5.1.6 on 2025-02-14 10:58

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0094_alter_languagecertificatevalue_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceReportQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validators', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('regex', 'Regex'), ('range', 'Range'), ('choice', 'Choice'), ('boolean', 'Boolean'), ('multiple_choice', 'Multiple Choice')], max_length=255), default=list, size=None, verbose_name='Validators')),
                ('validator_kwargs', models.JSONField(default=dict, help_text='A list of kwargs dictionaries', verbose_name='Validator kwargs')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('type', models.CharField(choices=[('true_false', 'True/False'), ('multiple_choice', 'Multiple Choice'), ('open_ended', 'Open Ended')], max_length=20, verbose_name='Type')),
                ('weight', models.PositiveIntegerField(default=1, verbose_name='Weight')),
            ],
            options={
                'verbose_name': 'Performance Report Question',
                'verbose_name_plural': 'Performance Report Questions',
            },
        ),
        migrations.RenameField(
            model_name='organizationemployeeperformancereport',
            old_name='text',
            new_name='report_text',
        ),
        migrations.RemoveField(
            model_name='organizationemployeeperformancereport',
            name='created_at',
        ),
        migrations.AddField(
            model_name='organizationemployeeperformancereport',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='organizationemployeeperformancereport',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='organizationemployeeperformancereport',
            name='report_summary',
            field=models.TextField(blank=True, null=True, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='organizationemployeeperformancereport',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('completed_by_organization', 'Completed By Organization'), ('completed_by_job_seeker', 'Completed By Job Seeker'), ('completed', 'Completed')], default='created', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='organizationemployeeperformancereportstatushistory',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('completed_by_organization', 'Completed By Organization'), ('completed_by_job_seeker', 'Completed By Job Seeker'), ('completed', 'Completed')], max_length=50, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='PerformanceReportAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(verbose_name='Value')),
                ('respondent', models.CharField(choices=[('job_seeker', 'Job Seeker'), ('organization', 'Organization')], max_length=20, verbose_name='Respondent')),
                ('organization_employee_performance_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='auth_account.organizationemployeeperformancereport', verbose_name='Organization Employee Performance Report')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='auth_account.performancereportquestion')),
            ],
            options={
                'verbose_name': 'Performance Report Answer',
                'verbose_name_plural': 'Performance Report Answers',
            },
        ),
    ]
