# Generated by Django 5.1.6 on 2025-02-14 11:56

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0095_performancereportquestion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationplatformmessage',
            name='created_at',
        ),
        migrations.AddField(
            model_name='organizationplatformmessage',
            name='assignee_type',
            field=models.CharField(choices=[('job_seeker', 'Job Seeker'), ('organization', 'Organization')], default='organization', max_length=50, verbose_name='Assignee'),
        ),
        migrations.AddField(
            model_name='organizationplatformmessage',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='organizationplatformmessage',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.DeleteModel(
            name='EmployeePlatformMessage',
        ),
    ]
