# Generated by Django 5.1.6 on 2024-09-07 16:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0096_remove_organizationplatformmessage_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancereportquestion',
            name='validators',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('regex', 'Regex'), ('range', 'Range'), ('choice', 'Choice')], max_length=255), default=list, size=None, verbose_name='Validators'),
        ),
    ]
