# Generated by Django 5.1.6 on 2025-02-15 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0097_alter_performancereportquestion_validators'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrganizationPlatformMessageLink',
            new_name='OrganizationPlatformMessageAttachment',
        ),
    ]
