# Generated by Django 5.1.6 on 2025-02-18 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0012_remove_course_type'),
        ('auth_account', '0098_rename_organizationplatformmessagelink_organizationplatformmessageattachment'),
        ('flex_blob', '0002_filemodel_uploaded_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationplatformmessageattachment',
            options={'verbose_name': 'Organization Platform Message Attachment', 'verbose_name_plural': 'Organization Platform Message Attachments'},
        ),
        migrations.RemoveField(
            model_name='organizationplatformmessageattachment',
            name='url',
        ),
        migrations.AlterField(
            model_name='organizationplatformmessageattachment',
            name='organization_platform_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='auth_account.organizationplatformmessage', verbose_name='Organization Platform Message'),
        ),
        migrations.CreateModel(
            name='PlatformMessageAttachmentCourse',
            fields=[
                ('organizationplatformmessageattachment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth_account.organizationplatformmessageattachment')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Platform Message Attachment Course',
                'verbose_name_plural': 'Platform Message Attachment Courses',
            },
            bases=('auth_account.organizationplatformmessageattachment',),
        ),
        migrations.CreateModel(
            name='PlatformMessageAttachmentCourseResult',
            fields=[
                ('organizationplatformmessageattachment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth_account.organizationplatformmessageattachment')),
                ('course_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.courseresult', verbose_name='Course Result')),
            ],
            options={
                'verbose_name': 'Platform Message Attachment Course Result',
                'verbose_name_plural': 'Platform Message Attachment Course Results',
            },
            bases=('auth_account.organizationplatformmessageattachment',),
        ),
        migrations.CreateModel(
            name='PlatformMessageAttachmentFile',
            fields=[
                ('organizationplatformmessageattachment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth_account.organizationplatformmessageattachment')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flex_blob.filemodel', verbose_name='File')),
            ],
            options={
                'verbose_name': 'Platform Message Attachment File',
                'verbose_name_plural': 'Platform Message Attachment Files',
            },
            bases=('auth_account.organizationplatformmessageattachment',),
        ),
    ]
