# Generated by Django 5.1.6 on 2025-01-06 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0099_alter_organizationplatformmessageattachment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='available_jobs',
        ),
    ]
