# Generated by Django 5.1.6 on 2025-01-26 20:45

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0100_remove_profile_available_jobs'),
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('common', '0018_field_field_name_gin_trgm_ops_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='certificateandlicense',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='certificate_title_gin_trgm_ops', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='education',
            index=django.contrib.postgres.indexes.GinIndex(fields=['degree'], name='education_degree_gin_trgm_ops', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=django.contrib.postgres.indexes.GinIndex(fields=['raw_skills'], name='profile_raw_skills_trgm_ops'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=django.contrib.postgres.indexes.GinIndex(fields=['resume_json'], name='resume_json_gin_jsonb_ops', opclasses=['jsonb_path_ops']),
        ),
        migrations.AddIndex(
            model_name='workexperience',
            index=django.contrib.postgres.indexes.GinIndex(fields=['grade'], name='work_experience_grade_ops', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='workexperience',
            index=django.contrib.postgres.indexes.GinIndex(fields=['skills'], name='work_experience_skills_ops'),
        ),
        migrations.AddIndex(
            model_name='workexperience',
            index=django.contrib.postgres.indexes.GinIndex(fields=['job_title'], name='work_experience_job_title_ops', opclasses=['gin_trgm_ops']),
        ),
    ]
