# Generated by Django 5.1.3 on 2024-12-01 21:15

import blob.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(db_index=True, upload_to=blob.models.dynamic_upload_to, verbose_name='File')),
            ],
            options={
                'verbose_name': 'Base File',
                'verbose_name_plural': 'Base Files',
            },
        ),
    ]
