substitutions:
  _TAG_NAME: ${TAG_NAME:-$SHORT_SHA}
steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-django-setup'
    waitFor: ['-']
    args: [
      'build', '-t', 'gcr.io/$PROJECT_ID/job-seekers-django-setup:${_TAG_NAME}', 
      '-f', 'Dockerfile.setup', '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-django-setup'
    waitFor: ['build-django-setup']
    args: ['push', 'gcr.io/$PROJECT_ID/job-seekers-django-setup:${_TAG_NAME}']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-django-api'
    waitFor: ['push-django-setup']
    args: [
      'build', '-t', 'gcr.io/$PROJECT_ID/job-seekers-django-api:${_TAG_NAME}', 
      '-f', 'Dockerfile.backend', '.', 
      '--build-arg', 'BASE_IMAGE=gcr.io/$PROJECT_ID/job-seekers-django-setup:${_TAG_NAME}'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-django-pubsub'
    waitFor: ['push-django-setup']
    args: [
      'build', '-t', 'gcr.io/$PROJECT_ID/job-seekers-django-pubsub:${_TAG_NAME}', 
      '-f', 'Dockerfile.pubsub', '.',
      '--build-arg', 'BASE_IMAGE=gcr.io/$PROJECT_ID/job-seekers-django-setup:${_TAG_NAME}'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-django-api'
    waitFor: ['build-django-api']
    args: ['push', 'gcr.io/$PROJECT_ID/job-seekers-django-api:${_TAG_NAME}']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-django-pubsub'
    waitFor: ['build-django-pubsub']
    args: ['push', 'gcr.io/$PROJECT_ID/job-seekers-django-pubsub:${_TAG_NAME}']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'execute-django-setup'
    waitFor: ['push-django-setup']
    entrypoint: 'gcloud'
    args: [
      'run', 'jobs', 'deploy', 'job-seekers-django-setup',
      '--image', 'gcr.io/$PROJECT_ID/job-seekers-django-setup:${_TAG_NAME}',
      '--region', 'us-central1',
      '--execute-now',
      '--wait'
    ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-django-api'
    waitFor: ['push-django-api', 'execute-django-setup']
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'job-seekers-django-api',
      '--image', 'gcr.io/$PROJECT_ID/job-seekers-django-api:${_TAG_NAME}',
      '--region', 'us-central1',
    ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-django-pubsub-email'
    waitFor: ['push-django-pubsub', 'execute-django-setup']
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'job-seekers-django-pubsub-email',
      '--image', 'gcr.io/$PROJECT_ID/job-seekers-django-pubsub:${_TAG_NAME}',
      '--region', 'us-central1',
    ]

options:
  logging: CLOUD_LOGGING_ONLY
  env:
    - "DOCKER_BUILDKIT=1"
  dynamicSubstitutions: true


