steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-django-base'
    waitFor: ['-']
    args: [
      'build', '-t', 'gcr.io/$PROJECT_ID/job-seekers-django-base', 
      '-f', 'Dockerfile', '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-django-base'
    waitFor: ['build-django-base']
    args: ['push', 'gcr.io/$PROJECT_ID/job-seekers-django-base']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-django-api'
    waitFor: ['push-django-base']
    args: [
      'build', '-t', 'gcr.io/$PROJECT_ID/job-seekers-django-api', 
      '-f', 'Dockerfile.backend', '.', 
      '--build-arg', 'BASE_IMAGE=gcr.io/$PROJECT_ID/job-seekers-django-base'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-django-pubsub'
    waitFor: ['push-django-base']
    args: [
      'build', '-t', 'gcr.io/$PROJECT_ID/job-seekers-django-pubsub', 
      '-f', 'Dockerfile.pubsub', '.',
      '--build-arg', 'BASE_IMAGE=gcr.io/$PROJECT_ID/job-seekers-django-base'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-django-api'
    waitFor: ['build-django-api']
    args: ['push', 'gcr.io/$PROJECT_ID/job-seekers-django-api']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-django-pubsub'
    waitFor: ['build-django-pubsub']
    args: ['push', 'gcr.io/$PROJECT_ID/job-seekers-django-pubsub']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-django-api'
    waitFor: ['push-django-api']
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'job-seekers-django-api',
      '--image', 'gcr.io/$PROJECT_ID/job-seekers-django-api',
      '--region', 'us-central1',
    ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-django-pubsub-email'
    waitFor: ['push-django-api']
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'job-seekers-django-pubsub-email',
      '--image', 'gcr.io/$PROJECT_ID/job-seekers-django-pubsub',
      '--region', 'us-central1',
    ]

options:
  logging: CLOUD_LOGGING_ONLY
  env:
    - "DOCKER_BUILDKIT=1"


