# Generated by Django 5.1.4 on 2025-01-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushnotification',
            name='device',
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='device_token',
            field=models.CharField(default='token', max_length=255, verbose_name='Device Token'),
            preserve_default=False,
        ),
    ]
