# Generated by Django 5.1.4 on 2025-01-16 06:27

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import notification.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex_report', '0023_alter_template_created_date_and_more'),
        ('notification', '0002_remove_pushnotification_device_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('content_template', models.TextField(help_text=notification.models.get_template_help_text, verbose_name='Content Template')),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('saved_filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='flex_report.templatesavedfilter', verbose_name='Saved Filter')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
            },
        ),
        migrations.CreateModel(
            name='CampaignNotificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push'), ('in_app', 'In-App')], max_length=10, verbose_name='Notification Type')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='notification.campaign', verbose_name='Campaign')),
                ('notification_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_notifications', to='notification.notificationtemplate', verbose_name='Template')),
                ('notification_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_notification_types', to='notification.notificationtemplate', verbose_name='Notification Title')),
            ],
            options={
                'verbose_name': 'Campaign Notification',
                'verbose_name_plural': 'Campaign Notifications',
                'unique_together': {('notification_type', 'campaign')},
            },
        ),
        migrations.CreateModel(
            name='CampaignNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('notification', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_notifications', to='notification.notification', verbose_name='Notification')),
                ('campaign_notification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_notifications', to='notification.campaignnotificationtype', verbose_name='Campaign Notification Type')),
            ],
            options={
                'verbose_name': 'Campaign Notification Type',
                'verbose_name_plural': 'Campaign Notification Types',
            },
        ),
    ]
