# Generated by Django 5.1.4 on 2024-01-06 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_whatsappnotification_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaignnotification',
            options={'verbose_name': 'Campaign Notification', 'verbose_name_plural': 'Campaign Notification'},
        ),
        migrations.AlterModelOptions(
            name='campaignnotificationtype',
            options={'verbose_name': 'Campaign Notification Type', 'verbose_name_plural': 'Campaign Notification Types'},
        ),
    ]
