# Generated by Django 5.1.4 on 2025-01-20 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0007_alter_campaign_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaignnotificationtype',
            old_name='notification_template',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='campaignnotificationtype',
            old_name='notification_title',
            new_name='subject',
        ),
    ]
