# Generated by Django 5.1.4 on 2025-01-20 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0008_rename_notification_template_campaignnotificationtype_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignnotificationtype',
            name='body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_notification_bodies', to='notification.notificationtemplate', verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='campaignnotificationtype',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_notification_subjects', to='notification.notificationtemplate', verbose_name='Subject'),
        ),
    ]
