# Generated by Django 5.1.4 on 2025-01-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0009_alter_campaignnotificationtype_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
