# Generated by Django 5.1.5 on 2024-03-31 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0010_alter_campaign_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='crontab',
            field=models.CharField(blank=True, help_text="If you wish to make this campaign periodic, then go to <a href='https://crontab.guru/'>Crontab Halper</a> and copy-paste the crontab values.", max_length=255, null=True, verbose_name='Crontab'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='crontab_last_run',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Crontab Last Run'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sent At'),
        ),
    ]
