# Generated by Django 5.1.5 on 2025-01-27 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0011_campaign_crontab_campaign_crontab_last_run_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignnotification',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_notifications', to='notification.notification', verbose_name='Notification'),
        ),
    ]
