# Generated by Django 5.1.5 on 2024-04-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0012_alter_campaignnotification_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='max_attempts',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Max Attempts'),
        ),
    ]
