# Generated by Django 5.1.4 on 2025-01-28 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0014_userpushnotificationtoken_delete_userdevice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pushnotification',
            old_name='device_token',
            new_name='token',
        ),
        migrations.RenameField(
            model_name='userpushnotificationtoken',
            old_name='device_token',
            new_name='token',
        ),
    ]
