# Generated by Django 5.1.6 on 2024-09-30 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0016_campaign_is_scheduler_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaign",
            name="crontab_last_run",
        ),
    ]
