# Generated by Django 5.1.6 on 2025-03-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0017_remove_campaign_crontab_last_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignnotificationtype',
            name='notification_type',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push'), ('in_app', 'In-App')], max_length=10, verbose_name='Notification Type'),
        ),
        migrations.DeleteModel(
            name='WhatsAppNotification',
        ),
    ]
