# Generated by Django 5.1.4 on 2024-12-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvtemplate',
            name='footer_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Footer Path'),
        ),
    ]
