# Generated by Django 5.1.4 on 2024-12-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVRequiredContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
            ],
            options={
                'verbose_name': 'CV Context',
                'verbose_name_plural': 'CV Contexts',
            },
        ),
        migrations.DeleteModel(
            name='CVContext',
        ),
        migrations.AlterField(
            model_name='cvtemplate',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Title'),
        ),
    ]
