# Generated by Django 5.1.4 on 2024-12-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedcv',
            name='additional_sections',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Sections'),
        ),
        migrations.AddField(
            model_name='generatedcv',
            name='certifications',
            field=models.JSONField(blank=True, null=True, verbose_name='Certifications'),
        ),
        migrations.AddField(
            model_name='generatedcv',
            name='educations',
            field=models.JSONField(blank=True, null=True, verbose_name='Educations'),
        ),
        migrations.AddField(
            model_name='generatedcv',
            name='input_json',
            field=models.JSONField(blank=True, null=True, verbose_name='Input JSON'),
        ),
        migrations.AddField(
            model_name='generatedcv',
            name='work_experiences',
            field=models.JSONField(blank=True, null=True, verbose_name='Work Experiences'),
        ),
    ]
