# Generated by Django 5.1.4 on 2024-12-12 09:04

import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_cvfile'),
        ('flex_blob', '0002_filemodel_uploaded_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CVFile',
            new_name='GeneratedCV',
        ),
        migrations.AddField(
            model_name='cvtemplate',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='cvtemplate',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
