# Generated by Django 5.1.3 on 2024-12-05 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_cvrequiredcontext_delete_cvcontext_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CVRequiredContext',
        ),
    ]
