# Generated by Django 5.1.4 on 2025-01-03 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_generatedcvcontent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedcvcontent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_contents', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
