# Generated by Django 5.1.4 on 2025-01-03 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_alter_generatedcvcontent_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedcvcontent',
            name='about_me',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='About Me'),
        ),
        migrations.AddField(
            model_name='generatedcvcontent',
            name='headline',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Headline'),
        ),
    ]
