# Generated by Django 5.1.4 on 2025-01-03 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_generatedcvcontent_about_me_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedcvcontent',
            name='about_me',
            field=models.TextField(blank=True, null=True, verbose_name='About Me'),
        ),
    ]
