# Generated by Django 5.1.1 on 2023-11-14 15:37

import django.utils.timezone
import model_utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_alter_generatedcvcontent_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedcv',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='generatedcv',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
