# Generated by Django 5.1.4 on 2024-12-26 00:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VertexAIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Slug for the model', unique=True, verbose_name='Slug')),
                ('model_name', models.CharField(max_length=255, verbose_name='Model')),
                ('instruction', models.TextField(blank=True, help_text='Instructions for the model', null=True, verbose_name='Instruction')),
                ('temperature', models.FloatField(default=1.0, help_text='Temperature for the model', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Temperature')),
                ('max_tokens', models.IntegerField(default=8192, help_text='Max tokens for the model', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8192)], verbose_name='Max tokens')),
            ],
            options={
                'verbose_name': 'Vertex AI Model',
                'verbose_name_plural': 'Vertex AI Models',
            },
        ),
    ]
