# Generated by Django 5.1.1 on 2024-11-08 11:10

import common.validators
import computedfields.resolver
import criteria.models
import django.db.models.deletion
import markdownfield.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0012_remove_jobassessmentjob_job_assessment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=64, verbose_name='Service ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=criteria.models.job_assessment_logo_path, validators=[common.validators.ValidateFileSize(max=3)], verbose_name='Logo')),
                ('short_description', models.CharField(max_length=255, verbose_name='Short Description')),
                ('description', markdownfield.models.MarkdownField(rendered_field='description_rendered')),
                ('resumable', models.BooleanField(default=False, verbose_name='Resumable')),
            ],
            options={
                'verbose_name': 'Job Assessment',
                'verbose_name_plural': 'Job Assessments',
            },
        ),
        migrations.CreateModel(
            name='JobAssessmentJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=False, verbose_name='Required')),
                ('retry_interval', models.DurationField(blank=True, null=True, verbose_name='Retry Interval')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_assessment_jobs', to='common.job', verbose_name='Job')),
                ('job_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_assessment_jobs', to='criteria.jobassessment', verbose_name='Job Assessment')),
            ],
            options={
                'verbose_name': 'Job Assessment Job',
                'verbose_name_plural': 'Job Assessment Jobs',
                'unique_together': {('job_assessment', 'job')},
            },
        ),
        migrations.AddField(
            model_name='jobassessment',
            name='related_jobs',
            field=models.ManyToManyField(related_name='assessments', through='criteria.JobAssessmentJob', to='common.job', verbose_name='Related Jobs'),
        ),
        migrations.CreateModel(
            name='JobAssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('timeout', 'Timeout')], default='not_started', max_length=64, verbose_name='Status')),
                ('raw_score', models.JSONField(blank=True, null=True, verbose_name='Raw Score')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('score', models.CharField(blank=True, choices=[('average', 'Average'), ('good', 'Good'), ('greate', 'Great'), ('exceptional', 'Exceptional')], editable=False, max_length=32, null=True)),
                ('job_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='criteria.jobassessment', verbose_name='Job Assessment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_assessment_results', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Job Assessment Result',
                'verbose_name_plural': 'Job Assessment Results',
            },
            bases=(computedfields.resolver._ComputedFieldsModelBase, models.Model),
        ),
    ]
