# Generated by Django 5.1.3 on 2024-11-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobassessmentresult',
            name='score',
            field=models.CharField(blank=True, choices=[('average', 'Average'), ('good', 'Good'), ('great', 'Great'), ('exceptional', 'Exceptional')], editable=False, max_length=32, null=True),
        ),
    ]
