# Generated by Django 5.1.1 on 2024-12-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobassessment',
            name='required',
            field=models.BooleanField(default=False, verbose_name='Required'),
        ),
    ]
