# Generated by Django 5.1.4 on 2024-12-10 21:49

import common.validators
import criteria.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobassessment',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=criteria.models.job_assessment_logo_path, validators=[common.validators.ValidateFileSize(max=1)], verbose_name='Logo'),
        ),
    ]
