# Generated by Django 5.1.3 on 2024-11-10 17:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0002_alter_jobassessmentresult_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobassessmentresult',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Order ID'),
        ),
    ]
