# Generated by Django 5.1.4 on 2024-12-21 09:03

import common.validators
import criteria.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0003_alter_jobassessment_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobassessment',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=criteria.models.job_assessment_logo_path, validators=[common.validators.ValidateFileSize(max=5)], verbose_name='Logo'),
        ),
    ]
