# Generated by Django 5.1.3 on 2024-11-10 17:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("criteria", "0003_jobassessmentresult_order_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobassessment",
            old_name="service_id",
            new_name="package_id",
        ),
    ]
