# Generated by Django 5.1.6 on 2025-02-20 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0004_alter_jobassessment_logo'),
        ('flex_blob', '0002_filemodel_uploaded_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAssessmentResultReportFile',
            fields=[
                ('filemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flex_blob.filemodel')),
                ('job_assessment_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_file', to='criteria.jobassessmentresult')),
            ],
            options={
                'verbose_name': 'Job Assessmen Result Report File',
                'verbose_name_plural': 'Job Assessmen Result Report Files',
            },
            bases=('flex_blob.filemodel',),
        ),
    ]
