# Generated by Django 5.1.3 on 2024-11-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0004_auto_20241110_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobassessment',
            name='package_id',
            field=models.CharField(max_length=64, verbose_name='Package ID'),
        ),
    ]
