# Generated by Django 5.1.6 on 2024-11-15 14:53

import django.utils.timezone
import model_utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0005_jobassessmentresultreportfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobassessmentresultreportfile',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='jobassessmentresultreportfile',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
