# Generated by Django 5.1.1 on 2024-11-11 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("criteria", "0005_alter_jobassessment_package_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobassessmentjob",
            name="retry_interval",
        ),
        migrations.AddField(
            model_name="jobassessment",
            name="count_limit",
            field=models.PositiveIntegerField(default=10, verbose_name="Count Limit"),
        ),
        migrations.AddField(
            model_name="jobassessment",
            name="retry_interval",
            field=models.DurationField(default=datetime.timedelta(days=7), verbose_name="Retry Interval"),
        ),
    ]
