# Generated by Django 5.1.3 on 2024-11-12 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0006_remove_jobassessmentjob_retry_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobassessment',
            name='time_limit',
            field=models.DurationField(default=datetime.timedelta(seconds=1800), verbose_name='Time Limit'),
        ),
    ]
