# Generated by Django 5.1.3 on 2024-11-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0008_jobassessmentresult_report_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobassessmentresult',
            name='report_url',
            field=models.URLField(blank=True, editable=False, null=True, verbose_name='Report URL'),
        ),
    ]
