# Generated by Django 5.1.3 on 2024-11-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0009_alter_jobassessmentresult_report_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobassessmentresult',
            name='raw_status',
            field=models.CharField(blank=True, choices=[('In Progress', 'In Progress'), ('Scheduled', 'Scheduled'), ('Complete', 'Complete'), ('Evaluation in Progress - \\d+ of \\d+ Completed', 'Evaluation in Progress - \\d+ of \\d+ Completed')], max_length=64, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='jobassessmentresult',
            name='status',
            field=models.CharField(blank=True, choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('timeout', 'Timeout')], default='not_started', editable=False, max_length=32, null=True),
        ),
    ]
