# Generated by Django 5.1.3 on 2024-11-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0011_alter_jobassessmentresult_raw_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobassessmentresult',
            name='raw_status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Scheduled', 'Scheduled'), ('Complete', 'Complete'), ('Evaluation in Progress - \\d+ of \\d+ Completed', 'Evaluation in Progress - \\d+ of \\d+ Completed')], default='Scheduled', max_length=64, verbose_name='Status'),
        ),
    ]
