# Generated by Django 5.1.3 on 2024-11-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0013_alter_jobassessmentresult_raw_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobassessmentresult',
            name='raw_status',
            field=models.CharField(default='In Progress', max_length=64, verbose_name='Status'),
        ),
    ]
