from account.assistant_test import KeywordClueWord, vector_search

weights = {
    "keywords": [["Python"], ["Django", "FastAPI", "Flask"]],
    "clue_words": [
        "Backend Developer",
        "Python Backend Developer",
        "Senior",
        "API",
        "RESTful API",
        "PostgreSQL",
        "ORM",
        "Django ORM",
        "SQLAlchemy",
        "Git",
        "pytest",
        "unittest",
        "DevOps",
        "CI/CD",
        "Infrastructure-as-code",
        "Docker",
        "Containerization",
        "Nginx",
        "Web Server",
        "AWS",
        "Google Cloud",
        "Azure",
        "Cloud Platforms",
        "Asynchronous Programming",
        "asyncio",
        "Celery",
        "Open-Source",
        "Message Queues",
        "RabbitMQ",
        "Kafka",
        "3+ years experience",
        "Remote",
        "US-based",
        "Schema Design",
        "Query Optimization",
        "Data Migration",
        "Code Reviews",
        "Automated Unit Tests",
        "Backend APIs",
        "Backend Systems",
        "Mobile App",
        "Scalable",
        "Reliable",
        "High-performance",
        "Well-documented",
        "Testable Code",
        "Problem-solving",
        "Communication Skills",
        "Team Environment",
        "High-quality Software",
        "Backend Development",
        "Relational Databases",
    ],
}

response = list(vector_search(KeywordClueWord.model_validate(weights)))
