# Generated by Django 5.1.3 on 2024-12-03 01:11

import flex_blob.fields
import flex_blob.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flex_blob", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basefilemodel",
            name="file",
            field=flex_blob.fields.DynamicFileField(
                db_index=True, upload_to=flex_blob.models.dynamic_upload_to, verbose_name="File"
            ),
        ),
    ]
