# Generated by Django 5.1.1 on 2023-03-06 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseresult',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='academy.course'),
        ),
    ]
