# Generated by Django 5.1.4 on 2023-03-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_alter_courseresult_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
