# Generated by Django 5.1.4 on 2023-03-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_course_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
    ]
