# Generated by Django 5.1.4 on 2024-12-16 09:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_course_is_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='courseresult',
            options={'verbose_name': 'Course Result', 'verbose_name_plural': 'Course Results'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='url',
        ),
        migrations.AlterUniqueTogether(
            name='courseresult',
            unique_together={('course', 'user')},
        ),
    ]
