# Generated by Django 5.1.4 on 2024-12-16 09:58

from django.db import migrations, models


def random_course_external_id(apps, schema_editor):
    Course = apps.get_model("academy", "Course")
    for course in Course.objects.all():
        import random

        if not course.external_id:
            course.external_id = random.random()
            course.save()


class Migration(migrations.Migration):
    dependencies = [
        ("academy", "0006_alter_course_options_alter_courseresult_options_and_more"),
    ]

    operations = [
        migrations.RunPython(random_course_external_id),
        migrations.AlterField(
            model_name="course",
            name="external_id",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
