# Generated by Django 5.1.4 on 2024-12-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0007_alter_course_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseresult',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='in_progress', max_length=50),
        ),
    ]
