# Generated by Django 5.1.4 on 2023-10-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0008_alter_courseresult_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
