# Generated by Django 5.1.1 on 2024-02-06 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0009_course_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseresult',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='results', to='academy.course'),
        ),
    ]
