# Generated by Django 5.1.6 on 2025-02-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0010_alter_courseresult_course'),
        ('common', '0015_alter_skill_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='industries',
            field=models.ManyToManyField(blank=True, related_name='courses', to='common.industry'),
        ),
    ]
