# Generated by Django 5.1.6 on 2024-09-06 14:12

from django.db import migrations


def convert_course_type_to_industries(apps, schema_editor):
    Course = apps.get_model("academy", "Course")
    for course in Course.objects.all():
        if course.type == "general":
            course.industries.clear()


class Migration(migrations.Migration):
    dependencies = [
        ("academy", "0011_alter_course_industries"),
    ]

    operations = [
        migrations.RunPython(convert_course_type_to_industries, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="course",
            name="type",
        ),
    ]
