# Generated by Django 5.1.4 on 2023-05-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('title',), 'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
    ]
