# Generated by Django 5.1.3 on 2024-12-03 14:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_university_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='website',
        ),
        migrations.AddField(
            model_name='university',
            name='websites',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None, verbose_name='Websites'),
        ),
    ]
