# Generated by Django 5.1.4 on 2024-12-21 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_job_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.skilltopic', verbose_name='Topic'),
        ),
    ]
