# Generated by Django 5.1.3 on 2024-12-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_remove_university_website_university_websites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
