# Generated by Django 5.1.1 on 2023-08-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_skill_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Job Benefit',
                'verbose_name_plural': 'Job Benefits',
            },
        ),
    ]
