# Generated by Django 5.1.1 on 2025-01-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_jobbenefit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='insert_type',
            field=models.CharField(choices=[('system', 'System'), ('ai', 'AI'), ('organization', 'Organization')], default='system', max_length=16, verbose_name='Insert Type'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Title'),
        ),
    ]
