# Generated by Django 5.1.1 on 2024-10-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_language_languageproficiencytest_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='languageproficiencytest',
            name='max_score',
            field=models.FloatField(default=9, verbose_name='Maximum Score'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='languageproficiencytest',
            name='min_score',
            field=models.FloatField(default=0, verbose_name='Minimum Score'),
            preserve_default=False,
        ),
    ]
