# Generated by Django 5.1.3 on 2024-12-07 14:46

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_field_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languageproficiencytest',
            name='max_score',
        ),
        migrations.RemoveField(
            model_name='languageproficiencytest',
            name='min_score',
        ),
        migrations.RemoveField(
            model_name='languageproficiencytest',
            name='overall_max_score',
        ),
        migrations.RemoveField(
            model_name='languageproficiencytest',
            name='overall_min_score',
        ),
        migrations.CreateModel(
            name='LanguageProficiencySkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validators', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('regex', 'Regex'), ('range', 'Range')], max_length=255), default=list, size=None, verbose_name='Validators')),
                ('validator_kwargs', models.JSONField(default=dict, help_text='A list of kwargs dictionaries', verbose_name='Validator kwargs')),
                ('skill_name', models.CharField(max_length=255, verbose_name='Skill Name')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.languageproficiencytest', verbose_name='Language Proficiency Test')),
            ],
            options={
                'verbose_name': 'Language Proficiency Skill',
                'verbose_name_plural': 'Language Proficiency Skills',
            },
        ),
        migrations.CreateModel(
            name='LanguageProficiencyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_proficiency_results', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='common.languageproficiencyskill', verbose_name='Skill')),
            ],
            options={
                'verbose_name': 'Language Proficiency Result',
                'verbose_name_plural': 'Language Proficiency Results',
            },
        ),
    ]
