# Generated by Django 5.1.4 on 2025-01-25 07:38

import django.db.models.deletion
from django.db import migrations, models


def populate_industry(apps, schema_editor):
    Job = apps.get_model("common", "Job")
    for job in Job.objects.all():
        job.industry = job.category.industry
        job.save()


def reverse_run(*args, **kwargs):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0005_alter_skill_insert_type_alter_skill_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="industry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.industry",
                verbose_name="Industry",
            ),
        ),
        migrations.RunPython(
            populate_industry,
            reverse_run,
            atomic=True,
        ),
    ]
