# Generated by Django 5.1.4 on 2024-12-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_remove_languageproficiencytest_max_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='languageproficiencyskill',
            name='slug',
            field=models.SlugField(default='', max_length=255, verbose_name='Slug'),
        ),
    ]
