# Generated by Django 5.1.4 on 2024-12-08 15:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_languageproficiencyskill_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languageproficiencyskill',
            name='validators',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('regex', 'Regex'), ('range', 'Range'), ('choice', 'Choice')], max_length=255), default=list, size=None, verbose_name='Validators'),
        ),
    ]
