# Generated by Django 5.1.1 on 2024-10-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='languageproficiencytest',
            name='overall_max_score',
            field=models.FloatField(default=1, verbose_name='Overall Maximum Score'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='languageproficiencytest',
            name='overall_min_score',
            field=models.FloatField(default=0, verbose_name='Overall Minimum Score'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='languageproficiencytest',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Title'),
        ),
    ]
