# Generated by Django 5.1.4 on 2024-12-08 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_languageproficiencyskill_validators'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LanguageProficiencyResult',
        ),
    ]
