# Generated by Django 5.1.4 on 2024-03-13 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_job_industry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='category',
        ),
        migrations.DeleteModel(
            name='JobCategory',
        ),
    ]
