# Generated by Django 5.1.1 on 2024-11-05 09:25

import common.models
import common.validators
import django.db.models.deletion
import markdownfield.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_skill_job_skill_level_skill_lft_skill_parent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=64, verbose_name='Service ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=common.models.job_assessment_logo_path, validators=[common.validators.ValidateFileSize(max=3)], verbose_name='Logo')),
                ('description', markdownfield.models.MarkdownField(rendered_field='description_rendered')),
                ('description_rendered', markdownfield.models.RenderedMarkdownField()),
                ('resumable', models.BooleanField(default=False, verbose_name='Resumable')),
            ],
            options={
                'verbose_name': 'Job Assessment',
                'verbose_name_plural': 'Job Assessments',
            },
        ),
        migrations.CreateModel(
            name='JobAssessmentJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=False, verbose_name='Required')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.job', verbose_name='Job')),
                ('job_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.jobassessment', verbose_name='Job Assessment')),
            ],
            options={
                'verbose_name': 'Job Assessment Job',
                'verbose_name_plural': 'Job Assessment Jobs',
                'unique_together': {('job_assessment', 'job')},
            },
        ),
        migrations.AddField(
            model_name='jobassessment',
            name='related_jobs',
            field=models.ManyToManyField(related_name='assessments', through='common.JobAssessmentJob', to='common.job', verbose_name='Related Jobs'),
        ),
    ]
