# Generated by Django 5.1.4 on 2024-12-08 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_delete_languageproficiencyresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languageproficiencyskill',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.languageproficiencytest', verbose_name='Language Proficiency Test'),
            preserve_default=False,
        ),
    ]
