# Generated by Django 5.1.5 on 2024-03-22 10:18

from django.db import migrations


def merge_duplicate_jobs(apps, schema_editor):
    from common.utils import fj, merge_relations

    from ..models import Job as JobModel

    Job: JobModel = apps.get_model("common", "Job")
    duplicate_jobs = Job.objects.all().difference(Job.objects.order_by(fj(Job.title)).distinct(fj(Job.title)))
    for job in duplicate_jobs:
        jobs = Job.objects.filter(**{fj(Job.title, "iexact"): job.title})
        merge_relations(job, *(target_objs := jobs[1:]))
        Job.objects.filter(pk__in=target_objs.values("pk")).delete()


def reverse(apps, scheme_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0008_remove_job_category_delete_jobcategory"),
    ]

    operations = [
        migrations.RunPython(
            merge_duplicate_jobs,
            reverse,
            atomic=True,
        )
    ]
