# Generated by Django 5.1.1 on 2024-11-06 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_jobassessment_jobassessmentjob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobassessmentjob',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_assessment_jobs', to='common.job', verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='jobassessmentjob',
            name='job_assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_assessment_jobs', to='common.jobassessment', verbose_name='Job Assessment'),
        ),
    ]
