# Generated by Django 5.1.5 on 2025-01-26 13:49

from django.db import migrations


def merge_duplicate_jobs(apps, schema_editor):
    from common.utils import merge_relations

    from ..models import Job as JobModel

    Job: JobModel = apps.get_model("common", "Job")
    duplicate_jobs = [
        # [[1223, "Aircraft Maintenance Engineer"], [-819, "Aircraft Maintenance Engineer (AME)"]],
        # [[-719, "Blasting Technician"], [492, "Blast Technician"]],
        # [[-433, "Cabinetmaker"], [1001, "Cabinet Maker"]],
        # [[-1683, "Chief Operating Officer (COO)"], [512, "Chief Operations Officer (COO)"]],
        # [[562, "Database Administrator"], [-1274, "Database Administrator (DBA)"]],
        # [[-991, "Process Development Engineer"], [1033, "Process Development Engineer (Paper)"]],
        # [[-1017, "Product Development Specialist"], [956, "Product Development Specialist (Food)"]],
    ]
    for job in duplicate_jobs:
        source_pk = min(i[0] for i in job)
        target_pks = [i[0] for i in job if i[0] != source_pk]
        merge_relations(
            Job.objects.get(pk=abs(source_pk)),
            *(target_objs := Job.objects.filter(pk__in=target_pks)),
        )
        target_objs.delete()


def reverse(*args, **kwargs):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0009_merge_job_positions"),
    ]

    operations = [
        migrations.RunPython(
            merge_duplicate_jobs,
            reverse,
            atomic=True,
        )
    ]
