# Generated by Django 5.1.4 on 2024-12-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_alter_languageproficiencyskill_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languageproficiencyskill',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Slug'),
        ),
    ]
