# Generated by Django 5.1.4 on 2024-04-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_duplicate_job_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='industries',
            field=models.ManyToManyField(related_name='jobs', to='common.industry', verbose_name='Industries'),
        ),
    ]
