# Generated by Django 5.1.4 on 2024-12-08 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_alter_languageproficiencyskill_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languageproficiencyskill',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='common.languageproficiencytest', verbose_name='Language Proficiency Test'),
        ),
    ]
