# Generated by Django 5.1.1 on 2024-11-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_alter_jobassessmentjob_job_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobassessment',
            name='description_rendered',
        ),
        migrations.AddField(
            model_name='jobassessment',
            name='short_description',
            field=models.CharField(default='test', max_length=255, verbose_name='Short Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobassessmentjob',
            name='retry_interval',
            field=models.DurationField(blank=True, null=True, verbose_name='Retry Interval'),
        ),
    ]
