# Generated by Django 5.1.1 on 2024-11-08 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0036_remove_profile_job_assessment_bookmarks_and_more'),
        ('common', '0011_remove_jobassessment_description_rendered_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='jobassessmentjob',
        #     name='job_assessment',
        # ),
        migrations.AlterUniqueTogether(
            name='jobassessmentjob',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='jobassessmentjob',
            name='job',
        ),
        migrations.DeleteModel(
            name='JobAssessment',
        ),
        migrations.DeleteModel(
            name='JobAssessmentJob',
        ),
    ]
