# Generated by Django 5.1.4 on 2025-01-30 14:55

from django.db import migrations


def migrate_industry_to_m2m(apps, schema_editor):
    Job = apps.get_model("common", "Job")

    for job in Job.objects.all():
        if job.industry:
            job.industries.add(job.industry)


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0011_job_industries"),
    ]

    operations = [
        migrations.RunPython(migrate_industry_to_m2m, migrations.RunPython.noop),
    ]
