# Generated by Django 5.1.3 on 2024-11-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_remove_jobassessmentjob_job_assessment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='insert_type',
            field=models.CharField(choices=[('system', 'System'), ('ai', 'AI')], default='system', max_length=10, verbose_name='Insert Type'),
        ),
    ]
