# Generated by Django 5.1.1 on 2024-11-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_skill_insert_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='require_appearance_data',
            field=models.BooleanField(default=False, verbose_name='Require Appearance Data'),
        ),
    ]
