# Generated by Django 5.1.4 on 2025-02-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_merge_skill_titles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='title',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Title'),
        ),
    ]
