# Generated by Django 5.1.1 on 2024-11-13 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0043_profile_native_language_and_more'),
        ('common', '0014_job_require_appearance_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
    ]
