# Generated by Django 5.1.6 on 2024-09-05 11:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_alter_skill_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languageproficiencyskill',
            name='validators',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('regex', 'Regex'), ('range', 'Range'), ('choice', 'Choice'), ('boolean', 'Boolean'), ('multiple_choice', 'Multiple Choice')], max_length=255), default=list, size=None, verbose_name='Validators'),
        ),
    ]
