# Generated by Django 5.1.3 on 2024-11-18 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_delete_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='level',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='tree_id',
        ),
    ]
