# Generated by Django 5.1.3 on 2024-11-18 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_remove_skill_level_remove_skill_lft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.jobindustry', verbose_name='Industry'),
        ),
    ]
