# Generated by Django 5.1.3 on 2024-11-18 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_skill_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='industry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.jobindustry', verbose_name='Industry'),
            preserve_default=False,
        ),
    ]
