# Generated by Django 5.1.6 on 2025-01-26 20:00

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import BtreeGinExtension, TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0017_alter_languageproficiencyskill_validators"),
    ]

    operations = [
        TrigramExtension(),
        BtreeGinExtension(),
        migrations.AddIndex(
            model_name="field",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"], name="field_name_gin_trgm_ops", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="industry",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title"], name="industry_title_gin_trgm_ops", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title"], name="job_title_gin_trgm_ops", opclasses=["gin_trgm_ops"]
            ),
        ),
    ]
