# Generated by Django 5.1.3 on 2024-11-18 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_alter_skill_industry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='industry',
        ),
        migrations.CreateModel(
            name='SkillTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.jobindustry', verbose_name='Industry')),
            ],
            options={
                'verbose_name': 'Skill Topic',
                'verbose_name_plural': 'Skill Topics',
            },
        ),
    ]
