# Generated by Django 5.1.3 on 2024-11-18 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_remove_skill_industry_skilltopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.skilltopic', verbose_name='Topic'),
            preserve_default=False,
        ),
    ]
