# Generated by Django 5.1.3 on 2024-11-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_skill_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
