# Generated by Django 5.1.3 on 2024-11-18 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_alter_skill_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='job',
        ),
    ]
