# Generated by Django 5.1.3 on 2024-11-18 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_remove_skill_job'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobIndustry',
            new_name='Industry',
        ),
        migrations.AlterModelOptions(
            name='industry',
            options={'verbose_name': 'Industry', 'verbose_name_plural': 'Industries'},
        ),
        migrations.RemoveField(
            model_name='job',
            name='industry',
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='industry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.industry', verbose_name='Industry'),
            preserve_default=False,
        ),
    ]
